add regulated terminal in 2WT form
gridsuite/gridstudy-app pull request #1086
Opened 2023-02-09 08:45 UTC by AbdelHedhili

Signed-off-by: Abdelsalem <abdelsalem.hedhili@rte-france.com>

2023-02-10 08:31 UTC, archendel requested changes
some remarks

2023-02-10 08:31 UTC, archendel commented on src/components/refactor/dialogs/two-windings-transformer-creation/ratio-tap-changer-pane/ratio-tap-changer-pane.js
> +    };
useCallback since it depends on component state ?

2023-02-10 08:31 UTC, archendel commented on src/components/refactor/dialogs/two-windings-transformer-creation/two-windings-transformer-creation-dialog.js
> +                            : undefined,
this condition is hard to understand, make a function

2023-02-10 08:31 UTC, archendel commented on src/components/refactor/dialogs/two-windings-transformer-creation/two-windings-transformer-creation-dialog.js
> +                            : undefined,
this condition is hard to understand, make a function

2023-02-10 08:31 UTC, archendel commented on src/components/refactor/dialogs/two-windings-transformer-creation/two-windings-transformer-creation-dialog.js
> +                            : undefined,
this condition is hard to understand, make a function

2023-02-10 08:31 UTC, archendel commented on src/components/refactor/dialogs/two-windings-transformer-creation/two-windings-transformer-creation-dialog.js
> +                    regulationType: undefined,
we should not use "undefined" values with react hook form

2023-02-10 08:31 UTC, archendel commented on src/components/refactor/dialogs/two-windings-transformer-creation/two-windings-transformer-creation-dialog.js
> +                    regulationType: undefined,
we should not use "undefined" values with react hook form

2023-02-10 08:31 UTC, archendel commented on src/components/refactor/dialogs/two-windings-transformer-creation/two-windings-transformer-creation-dialog.js
> +                            : undefined,
this condition is hard to understand, make a function

2023-02-13 08:37 UTC, AbdelHedhili commented on src/components/refactor/dialogs/two-windings-transformer-creation/phase-tap-changer-pane/phase-tap-changer-pane.js
> +                                    REGULATION_TYPES.DISTANT.id && (
indeed, removed

2023-02-13 08:39 UTC, AbdelHedhili commented on src/components/refactor/dialogs/two-windings-transformer-creation/phase-tap-changer-pane/phase-tap-changer-pane.js
> +    const isVoltageRegulationOn = () => {
done

2023-02-14 14:01 UTC, archendel approved these changes

2023-02-14 14:55 UTC, YenguiSeddik approved these changes

2023-02-14 15:34 UTC, merged