Delete equipment from map and SLD
gridsuite/gridstudy-app pull request #1107
Opened 2023-02-17 12:48 UTC by archendel

2023-02-21 15:17 UTC, laurgarn approved these changes
Tests: OK
Code: OK
Console: OK

2023-02-21 16:22 UTC, Meklo approved these changes

2023-02-22 08:12 UTC, dbraquart requested changes
code review: pending
tests:
- KO : delete item is displayed twice for the lines in the map, and for lines/2WT in the SLD
- question / KO: can we delete a HVDC conversion station ? If we do so, we've got an error message

2023-02-22 12:32 UTC, dbraquart approved these changes
tests: all good
review: minor remarks about naming

2023-02-28 09:45 UTC, archendel commented on src/components/menus/base-equipment-menu.js
> +const ItemDeleteEquipment = ({
done for both

2023-02-28 09:45 UTC, archendel commented on src/components/menus/base-equipment-menu.js
> +    const equipmentsWithBranch = [
done

2023-02-28 09:45 UTC, archendel commented on src/components/menus/base-equipment-menu.js
> +    const equipmentsNotDeletable = [
done

2023-02-28 10:46 UTC, merged