feat:migrate equipment deletion
gridsuite/gridstudy-app pull request #1167
Opened 2023-03-14 16:10 UTC by laurgarn

2023-03-14 16:47 UTC, ayolab requested changes

2023-03-14 16:47 UTC, ayolab commented on src/components/refactor/dialogs/equipment-deletion/equipment-deletion-dialog.js
> +            console.debug('EquipmentDeletion.fromEditDataToForm', editData);
remove this

2023-03-15 08:19 UTC, laurgarn commented on src/components/refactor/dialogs/equipment-deletion/equipment-deletion-form.js
> +    useEffect(() => {
Done.

2023-03-15 08:19 UTC, laurgarn commented on src/components/refactor/dialogs/equipment-deletion/equipment-deletion-dialog.js
> +            console.debug('EquipmentDeletion.fromEditDataToForm', editData);
Done

2023-03-15 08:19 UTC, laurgarn commented on src/components/refactor/dialogs/equipment-deletion/equipment-deletion-dialog.js
> +    [TYPE]: null,
Done

2023-03-15 10:36 UTC, ayolab approved these changes

2023-03-15 14:11 UTC, archendel approved these changes

2023-03-17 10:04 UTC, merged