Add nested menus in tree node menu
gridsuite/gridstudy-app pull request #1237
Opened 2023-04-21 10:55 UTC by ghazwarhili

2023-04-25 11:14 UTC, sBouzols requested changes

2023-04-25 11:14 UTC, sBouzols commented on src/components/graph/menus/create-node-menu.js
> +                const isCreate = item.id === 'createNetworkModificationNode';
This is strnage...
Maybe you should have a NODE_MENU_ITEMS definition containing some nested Menu
ex:
```
const NODE_MENU_ITEMS = {
        MENU_ITEM_A: {
            onRoot: true,
            action: () => foo(),
            id: 'myIdA',
            subMenuItems: {
                MENU_ITEM_B: {
                    id: tutu,
                    ...
                }
            }
        },
```
Then you could create a recursive function, which will render the corresponding JSX Menu with `NestedMenuItem` when needed (i.e when subMenuItems !== undefined and has at least one menu item...)

2023-04-25 11:14 UTC, sBouzols commented on src/translations/en.json
> +    "pasteNetworkModificationNodeOnNewBranch": "Paste node",
fix key -> pasteNetworkModificationNode~~OnNewBranch~~

2023-04-25 11:14 UTC, sBouzols commented on package.json
> +        "mui-nested-menu": "^3.2.1",
please keep the form ^3.0.0 in here, even if you should update the dep in package-lock

2023-04-25 11:14 UTC, sBouzols commented on package.json
> +        "react-flow-renderer": "10.3.17",
revert this change

2023-04-25 11:14 UTC, sBouzols commented on package-lock.json
> +            "version": "3.2.1",
If you need to upgrade to this version, please note in comment of the PR why.

2023-04-28 12:58 UTC, sBouzols commented on src/components/graph/menus/create-node-menu.js
> +                                    {Object.values(item.subMenuItems).map(
This is not recursive. If we add `subMenuItems` in an item which is already a sub menu item then it won't work.

2023-04-28 12:58 UTC, sBouzols commented on src/components/graph/menus/create-node-menu.js
> +        minWidth: 300,
removed OK

2023-05-02 16:20 UTC, dbraquart requested changes
code review: ok. It does not support recursive nested menus, but this is acceptable for now

tests: works fine, but 1 remark:
1) If clipboard is empty, maybe "Paste node" whole menu should be disabled ?

console:
1) "Warning: Each child in a list should have a unique "key" prop."
-> This is an important React warning that must be adressed
2) "MUI: The Menu component doesn't accept a Fragment as a child. Consider providing an array instead."

2023-05-23 15:12 UTC, dbraquart reviewed
code: ok
test: ok

2023-05-23 15:14 UTC, dbraquart approved these changes

2023-05-25 13:35 UTC, sBouzols requested changes
Anti Pattern : Nested component

2023-05-25 13:35 UTC, sBouzols commented on src/components/graph/menus/create-node-menu.js
> +    const SubMenuItem = ({ item }) => {
It is forbidden to create nested component in another component. Anti pattern, performance issue.
Move this component definintion in another file or outside of the CreateNodeMenu component.
Or create a render function instead.
Also `SubMenuItem` is misnamed. Something like `NodeMenuItem` is better

2023-05-25 13:35 UTC, sBouzols commented on src/components/graph/menus/create-node-menu.js
> +                                        (item) => {
use another name here to avoid confusion with the existing `item` variable.
Something like `(subItem)` should be ok

2023-06-01 09:27 UTC, sBouzols commented on src/components/graph/menus/create-node-menu.js
> +                const isCreate = item.id === 'createNetworkModificationNode';
done

2023-06-01 10:34 UTC, sBouzols approved these changes
Code Review OK
Tests OK
Console Warning Check OK

2023-06-02 08:47 UTC, merged