Specific settings : Handle NaN values.
gridsuite/gridstudy-app pull request #1307
Opened 2023-05-23 15:14 UTC by AAJELLAL

2023-05-23 15:37 UTC, FranckLecuyer requested changes

2023-05-23 15:37 UTC, FranckLecuyer commented on src/components/dialogs/parameters/load-flow-parameters.js
> +    const getObjectWithoutNanValuse = useCallback((initialObject) => {
Typo: getObjectWithoutNanValues

2023-05-23 15:48 UTC, AAJELLAL commented on src/components/dialogs/parameters/load-flow-parameters.js
> +    const getObjectWithoutNanValuse = useCallback((initialObject) => {
Done

2023-05-23 15:50 UTC, FranckLecuyer approved these changes

2023-05-23 22:16 UTC, ayolab approved these changes

2023-05-23 22:16 UTC, ayolab commented on src/components/dialogs/parameters/load-flow-parameters.js
> +                    : initialObject[key]
```suggestion
                (initialObject[key] = Number.isNaN(initialObject[key])
                    ? null
                    : initialObject[key])
```

2023-05-23 22:16 UTC, ayolab commented on src/components/dialogs/parameters/load-flow-parameters.js
> +            getObjectWithoutNanValuse,
```suggestion
            getObjectWithoutNanValues,
```

2023-05-24 08:53 UTC, AAJELLAL commented on src/components/dialogs/parameters/load-flow-parameters.js
> +                    : initialObject[key]
Done

2023-05-24 09:05 UTC, merged