Add shunt compensator modification
gridsuite/gridstudy-app pull request #1351
Opened 2023-06-12 11:54 UTC by YenguiSeddik

2023-06-13 14:03 UTC, Meklo commented on src/components/dialogs/network-modifications/shunt-compensator/characteristics-pane/characteristics-form-utils.js
>      [SHUNT_COMPENSATOR_TYPE]: yup.string().when([CHARACTERISTICS_CHOICE], {
Shouldn't this field be nullable it's a modification situation ?

2023-06-16 14:39 UTC, dbraquart requested changes
code: ok
console: no warning
tests:
1) Issues:
- "Name", "susceptance" and "A at nominal voltage" fields must be nullable (have a cross to empty the field)
- when we create a modification, and just select an Id, we can validate the form wihout any modification.
In this case we create a modification in db with a change on "voltage_level_id".
We can realize the modification, but there is nothing to do (no logs).

2) remarks:
- we should use the same label in creation and modification sub-menus (same in EN but different in FR)

2023-06-20 11:45 UTC, dbraquart approved these changes
code: ok
console: ok
tests: almost ok
- we still can validate an "empty" modification, but I think it can be resolve later by an existing US.

2023-06-23 12:42 UTC, sBouzols approved these changes
Code Review OK
Tests OK
Console Warning Check OK

2023-06-23 13:28 UTC, EstherDarkish reviewed
Found an edge case that is maybe a bug

2023-06-26 08:22 UTC, EstherDarkish approved these changes

2023-06-26 10:35 UTC, merged