Add creation battery form
gridsuite/gridstudy-app pull request #1368
Opened 2023-06-15 07:17 UTC by ghazwarhili

2023-06-15 09:54 UTC, ghelloumi commented on src/components/dialogs/network-modifications/battery/creation/battery-creation-dialog.js
> +const BatteryCreationDialog = ({
Can you add propTypes please?

2023-06-15 09:54 UTC, ghelloumi commented on src/components/dialogs/network-modifications/battery/creation/battery-creation-dialog.js
> +    const equipmentPath = 'generators';
it is better to make constants outside the component (performance impact due to the renders)
 const EQUIPMENT_PATH = 'generators';

2023-06-15 09:54 UTC, ghelloumi commented on src/utils/rest-api.js
> +        body: JSON.stringify({
you can use 
`       body: JSON.stringify({
            type: MODIFICATION_TYPES.BATTERY_CREATION.type,
            equipmentId: id,
            equipmentName: name,
            voltageLevelId,
            busOrBusbarSectionId,
            connectionName,
            connectionDirection,
            connectionPosition,
            minActivePower,
            maxActivePower,
            isReactiveCapabilityCurveOn,
            minimumReactivePower,
            maximumReactivePower,
            reactiveCapabilityCurvePoints: reactiveCapabilityCurve,
            activePowerSetpoint,
            reactivePowerSetpoint,
            participate: frequencyRegulation,
            droop,
        }),`

2023-07-05 13:32 UTC, EstherDarkish commented on src/components/utils/field-constants.js
> +export const REACTIVE_POWER = 'reactivePowerSetpoint';
There is already in the file theses entries : 
`export const ACTIVE_POWER_SET_POINT = 'activePowerSetpoint';`
`export const REACTIVE_POWER_SET_POINT = 'reactivePowerSetpoint';`

2023-07-05 13:32 UTC, EstherDarkish commented on src/translations/en.json
>      "ModifyGenerator": "Modify generator",
why not "Create battery" instead of "Battery" ?

2023-07-05 13:32 UTC, EstherDarkish commented on src/translations/fr.json
>      "ModifyGenerator": "Modifier un groupe",
Why not "Créer une batterie" instead of "Batterie" ?

2023-07-10 12:46 UTC, ayolab requested changes

2023-07-10 12:46 UTC, ayolab commented on src/components/dialogs/network-modifications/battery/creation/battery-creation-dialog.js
> +import { FetchStatus } from 'utils/rest-api';
```suggestion

```
remove this

2023-07-10 15:05 UTC, ayolab approved these changes

2023-07-17 13:54 UTC, merged