Minor Changes on generation dispatch form
gridsuite/gridstudy-app pull request #1378
Opened 2023-06-20 10:01 UTC by ghelloumi

**Before:**
![image](https://github.com/gridsuite/gridstudy-app/assets/19638693/ac33ad89-32af-4125-8179-f59c396cb7e0)

**After:**
![image](https://github.com/gridsuite/gridstudy-app/assets/19638693/70071851-c58c-4204-a76b-a6e511af83d6)

2023-06-20 13:38 UTC, Walid-Sahnoun reviewed
code ok
test ok
ergonomic proposition: 
disable drag&drop mechanism and icon  when only 1 line exist
change tooltip in buttons from "add row" "delete row" "move up row" "move down row" 
to "add", "delete" , "move up" "move down" 
add tooltip on folder "open" or "choose element"

2023-07-12 15:37 UTC, trikimahdi requested changes

2023-07-12 15:37 UTC, trikimahdi commented on src/components/dialogs/network-modifications/generation-dispatch/generation-dispatch-form.js
> +                    name={`${GENERATORS_WITHOUT_OUTAGE}`}
you can remove the  `${}`

2023-07-19 08:47 UTC, ghelloumi commented on src/components/dialogs/network-modifications/generation-dispatch/generation-dispatch-form.js
> +                    name={`${GENERATORS_WITHOUT_OUTAGE}`}
done, thank you

2023-07-19 09:01 UTC, Walid-Sahnoun approved these changes
review ok
test ok

2023-07-25 11:29 UTC, merged