Adjust AgGrid results for LF and AS
gridsuite/gridstudy-app pull request #1393
Opened 2023-06-27 11:45 UTC by souissimai

2023-06-27 14:09 UTC, trikimahdi approved these changes
tests ok
code ok

2023-06-27 14:39 UTC, ghelloumi commented on src/components/security-analysis-result.js
> +                flex: 1,
you can add flex: 1 only on columnDefs
for both renderTableNmKConstraints and renderTableNmKContingencies (then, you can remove width for columnsNmKContingencies)

2023-06-28 09:55 UTC, archendel requested changes
Load sorting is not sorting correctly
It should sort data as numbers but sorts them alphabetically

2023-06-28 11:40 UTC, ghelloumi approved these changes
tests ok
code ok

2023-06-28 13:55 UTC, archendel approved these changes

2023-06-28 14:14 UTC, merged