Add phase tap to twt modification
gridsuite/gridstudy-app pull request #1405
Opened 2023-07-03 12:33 UTC by Meklo

2023-07-13 14:41 UTC, Walid-Sahnoun commented on src/components/dialogs/network-modifications/two-windings-transformer/creation/tap-changer-pane/phase-tap-changer-pane/phase-tap-changer-pane-steps.js
> +    modification = false,
rename "modification" => "isModifcation" or "isTwtModification" be better

2023-07-13 14:43 UTC, Walid-Sahnoun commented on src/components/dialogs/network-modifications/two-windings-transformer/creation/tap-changer-pane/phase-tap-changer-pane/phase-tap-changer-pane-utils.js
> +const phaseTapChangerValidationSchema = (modification, id) => ({
same here

2023-07-24 16:51 UTC, dbraquart requested changes
code: minor changes requested

tests:
- I got the same "updateResource()" issue in incremental mode, then I had to use locally this [PR](https://github.com/powsybl/powsybl-network-store/pull/340)
(other workaround: rebuild the whole node to make sure the resource is flushed to db).
- I think the deadband adornement (MV) is bad. To be checked with PO. This is the same in the Ratio tab.
- issue. test case:
	- create a 2wt modification on unknown id "ttt"
	- enable phase tap changer
	- set "current limiter" regulation, local, 20A, 0.2 (deadband), Side2
	- save/open, the content is not good (regulation became Remote)

2023-07-31 17:55 UTC, dbraquart approved these changes
code: ok
tests: ok

2023-08-01 09:28 UTC, archendel approved these changes

2023-08-01 14:02 UTC, merged