Update section count in shunt compensator creation
gridsuite/gridstudy-app pull request #1412
Opened 2023-07-06 15:07 UTC by Walid-Sahnoun

2023-07-10 08:46 UTC, FranckLecuyer requested changes

2023-07-10 08:46 UTC, FranckLecuyer commented on src/utils/rest-api.js
> +export function startLoadFlow(studyUuid, currentNodeUuid) {
Your rest-api.js file is not up to date : a lot of functions have already been moved to other files ....

2023-07-11 12:09 UTC, FranckLecuyer approved these changes

2023-07-12 11:40 UTC, ayolab approved these changes

2023-07-12 13:35 UTC, merged