Fix when new Colum on Config table added for Spreadsheet
gridsuite/gridstudy-app pull request #1446
Opened 2023-08-03 10:00 UTC by souissimai

2023-08-03 12:34 UTC, archendel commented on src/components/app.js
> +                                tabDefinition.length !== reordredParams.length
```suggestion
                                tabDefinition.length > reordredParams.length
```

We only treat the "new fields" case here, not the "remove fields" one

2023-08-09 09:29 UTC, SlimaneAmar requested changes

2023-08-09 09:29 UTC, SlimaneAmar commented on src/components/app.js
> +                for (let item of reorderedColumnsParams) {
Create a function

2023-08-10 07:26 UTC, archendel approved these changes
Test: OK
Code: OK

It might be nice one day to regroup those 3 config params into a single one to prevent desync bug

2023-08-10 07:52 UTC, merged