Add voltage init ratio tap transformers modifications
gridsuite/gridstudy-app pull request #1459
Opened 2023-08-08 09:17 UTC by FranckLecuyer

2023-08-09 14:29 UTC, ghazwarhili requested changes

2023-08-09 14:29 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/voltage-init-modification/voltage-init-modification-dialog.tsx
> +                                m.ratioTapChangerPosition,
if m is null ?
```
 if (m.ratioTapChangerPosition) {
row[RATIO_TAP_CHANGER_POSITION] = m.ratioTapChangerPosition;}
 if (m.legSide) {
row[LEG_SIDE] = m.legSide; }
```

2023-08-10 10:12 UTC, FranckLecuyer commented on src/components/dialogs/network-modifications/voltage-init-modification/voltage-init-modification-dialog.tsx
> +                                m.ratioTapChangerPosition,
Changed (and m cannot be null)

2023-08-11 06:49 UTC, ghazwarhili reviewed
code review : ok

2023-08-11 08:23 UTC, ghazwarhili approved these changes

2023-08-11 16:24 UTC, dbraquart requested changes
code: ok
tests: 
 - I cant see any transformer in the modification (reason of the CR).
 - maybe use the AgGrid option to fill the whole place available in the Form?

2023-08-16 07:28 UTC, FranckLecuyer commented
> code: ok tests:
> 
>     * I cant see any transformer in the modification (reason of the CR).
You should add transformers filters in : Settings --> Voltage profile initialization --> Equipment selection --> Variable transformers
Otherwise, no transformer ratio tap will be changed ...
> 
>     * maybe use the AgGrid option to fill the whole place available in the Form? (cf search for onGridReady={onGridReady})

2023-08-16 16:00 UTC, FranckLecuyer commented
> code: ok tests:
> 
>     * I cant see any transformer in the modification (reason of the CR).
You should add transformers filters in : Settings --> Voltage profile initialization --> Equipment selection --> Variable transformers
Otherwise, no transformer ratio tap will be changed ...
> 
>     * maybe use the AgGrid option to fill the whole place available in the Form? (cf search for onGridReady={onGridReady})


> code: ok tests:
> 
>     * 1 thing to improve : When tap changer position is 0, we display an empty (or null) value in the agGrid rather than "0". Can be tested with JUMEAY762:
> 
Fixed
> 
> ```
> INFO: 2 windings transformer with id=JUMEAY762 modified :
> INFO:      Ratio tap changer position : 0 -> 0
> ```

2023-08-17 08:56 UTC, dbraquart approved these changes
code: ok
tests: ok  (3WT not tested)

2023-08-17 09:06 UTC, merged