keep status and results after refresh
gridsuite/gridstudy-app pull request #1475
Opened 2023-08-16 10:03 UTC by anistouri

2023-08-16 13:11 UTC, ayolab approved these changes

2023-08-16 18:29 UTC, dbraquart requested changes
code: your code does not solve the pb
tests:
- it does not work all the time when we re-open a study: we may still lose the computation status and results (it happens when we reset the provider, see below)
- with this PR comes new issues:
	* at study opening, there are no more Rest Get call to xxx-default-provider
	* when we try to change the provider in LF/AS parameters form, the combobox is not updated

With or Without your PR (main branch), I observe at study opening that:
- they are many (normal) calls to get providers, provider, default-provider, parameters ...
- AND some abnormal POST methods to update the provider for the study, for several computations (lf/as/sensi) => this is the root cause (cf we must not call resetProvider() at line 415)

2023-08-16 19:27 UTC, dbraquart commented on src/components/dialogs/parameters/parameters.js
>                          resetProvider();
we must not call resetProvider at study opening

2023-08-18 08:16 UTC, dbraquart commented on src/components/dialogs/parameters/parameters.js
> +                const providerNames = Object.keys(provider);
we have to compare with all providers, like before

2023-08-21 14:31 UTC, merged