Fix the circular dependency of EQUIPMENT_TYPES
gridsuite/gridstudy-app pull request #1479
Opened 2023-08-18 12:39 UTC by flomillot

Fix the circular dependency by refactoring type and fetchers from EQUIPMENT_TYPES

2023-08-24 07:54 UTC, souissimai requested changes
please fix prettiers

2023-08-24 08:16 UTC, flomillot commented
> please fix prettiers

Done

2023-08-28 07:12 UTC, souissimai approved these changes

2023-08-28 08:34 UTC, ghelloumi approved these changes
test ok
code ok

2023-08-28 11:46 UTC, merged