Remove the custom cell renderer and format into a basic string instead
gridsuite/gridstudy-app pull request #1516
Opened 2023-09-01 16:01 UTC by flomillot

2023-09-07 08:47 UTC, EstherDarkish approved these changes
Code OK Tests OK

2023-09-07 09:24 UTC, anistouri requested changes
There are 2 tooltips on the "Properties" column, the custom tooltip and the one from AGGRID

2023-09-08 10:45 UTC, flomillot commented
> There are 2 tooltips on the "Properties" column, the custom tooltip and the one from AGGRID

Ah yes indeed the custom one appear after 3 seconds. I see with the PO which one we keep.

2023-09-08 14:04 UTC, anistouri approved these changes

2023-09-08 14:05 UTC, flomillot commented on src/components/spreadsheet/utils/config-tables.js
> +                // tooltipComponent: CustomTooltipKeyValue, // TODO uncomment / delete with US 2326
Yes you're right, I do it

2023-09-08 14:46 UTC, merged