[WIP]Check indexation status and reindex-all at start if needed
gridsuite/gridstudy-app pull request #1531
Opened 2023-09-06 14:54 UTC by sBouzols

2023-09-14 14:18 UTC, FranckLecuyer requested changes

2023-09-14 14:18 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "studyIndexationError": "L'indexation de l'étude a échouée.",
Typo: L'indexation de l'étude a échoué

2023-09-14 14:18 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "checkstudyIndexationError": "La récupération de l'état d'indexation de l'étude a échouée.",
Typo: 
checkStudyIndexationError
La récupération de l'état d'indexation de l'étude a échoué

2023-09-19 08:53 UTC, FranckLecuyer approved these changes

2023-09-25 14:26 UTC, sBouzols commented on src/components/study-container.js
> +                        ]) ?? firstSelectedNode;
revert to ||

2023-10-02 13:12 UTC, merged