Add an id to reactive limits component
gridsuite/gridstudy-app pull request #1545
Opened 2023-09-11 07:31 UTC by YenguiSeddik

2023-09-18 15:07 UTC, FranckLecuyer requested changes

2023-09-18 15:07 UTC, FranckLecuyer commented on src/components/dialogs/network-modifications/battery/creation/battery-creation-dialog.js
> +                    battery?.minMaxReactiveLimits?.minimumReactivePower ?? null,
battery?.minMaxReactiveLimits?.maximumReactivePower ?? null

2023-09-19 08:48 UTC, FranckLecuyer approved these changes

2023-09-20 16:36 UTC, Walid-Sahnoun approved these changes
code ok
test ok

2023-09-21 08:00 UTC, merged