Handle as result sorting
gridsuite/gridstudy-app pull request #1598
Opened 2023-09-28 07:24 UTC by AAJELLAL

2023-09-29 11:23 UTC, etiennehomer requested changes

2023-09-29 11:23 UTC, etiennehomer commented on src/components/results/shortcircuit/shortcircuit-analysis-result-table.tsx
> +                headerName: intl.formatMessage({ id: 'deltaCurrentIpMax' }),
Change the column order

2023-09-29 13:27 UTC, AAJELLAL commented on src/components/results/shortcircuit/shortcircuit-analysis-result-table.tsx
> +                headerName: intl.formatMessage({ id: 'deltaCurrentIpMax' }),
Done

2023-09-29 17:16 UTC, etiennehomer approved these changes

2023-10-02 08:47 UTC, anistouri approved these changes

2023-10-02 09:27 UTC, merged