Permanant delete stashed modification
gridsuite/gridstudy-app pull request #1748
Opened 2023-11-29 10:12 UTC by lilian-houdelet

2023-11-29 21:26 UTC, souissimai commented on src/components/dialogs/restore-modification-dialog.js
> +    const [openAlert, setOpenAlert] = useState(false);
const [popupConfirmDeletion, setPopupConfirmDeletion] = useState(false);

2023-11-29 21:34 UTC, souissimai commented on src/components/dialogs/restore-modification-dialog.js
> +        setToggleSelectAll((prev) => !prev);
setToggleSelectAllStashedModifications : suggestion to rename it

2023-11-29 21:48 UTC, souissimai commented on src/components/dialogs/restore-modification-dialog.js
> +                                            modificationsToRestore.length
I believe a renaming is in order, given that we can now select stashed modifications to either restore or permanently delete them. My suggestion is to replace it by "stashedModifications"

2023-11-29 21:55 UTC, souissimai commented on src/components/dialogs/restore-modification-dialog.js
>          onClose();
```suggestion
    const handleDelete = () => {
        setOpenAlert(false);
        const selectedModificationsUuidToDelete = [
            ...selectedItems.values(),
        ].map((item) => item.uuid);
        deleteModifications(
            studyUuid,
            currentNode.id,
            selectedModificationsUuidToDelete
        );
        handleClose();
    };```

2023-11-29 22:01 UTC, souissimai commented on src/components/dialogs/restore-modification-dialog.js
> +    const handleDelete = () => {
const selectedModificationsUuidsToDelete = [
            ...selectedItems.values(),
        ].map((item) => item.uuid);

2023-11-30 16:37 UTC, souissimai approved these changes
test ok code ok

2023-12-12 08:54 UTC, ayolab requested changes
there is some warnings that need to be fixed

2023-12-12 09:54 UTC, ayolab approved these changes

2023-12-12 16:10 UTC, merged