Add Possibility to permanantly delete node + restore multiple nodes
gridsuite/gridstudy-app pull request #1749
Opened 2023-11-30 12:41 UTC by lilian-houdelet

2023-12-01 10:05 UTC, AbdelHedhili requested changes
There is a bug : 
 - create a subtree of at least 2 nodes
 - delete that subtree
 - delete it permanently 
 - go in the restore/delete popup and you will see that only the first node was permanently deleted and not the whole subtree

2023-12-01 10:11 UTC, lilian-houdelet commented on src/translations/en.json
> -    "Connected": "Connected",
Duplicate key, if I'm not wrong

2023-12-01 10:14 UTC, AbdelHedhili commented on src/translations/en.json
> -    "Connected": "Connected",
Indeed, good catch, however we avoid doing changes that isn't related to the feature/bug you are working on in the same PR. Move this into another PR please.

2023-12-04 09:40 UTC, AbdelHedhili approved these changes

2023-12-15 08:18 UTC, souissimai approved these changes
seems ok

2023-12-18 11:09 UTC, merged