Inject informations into about dialog
gridsuite/gridstudy-app pull request #1750
Opened 2023-11-30 17:14 UTC by Tristan-WorkGH

Dependent of:
* gridsuite/deployment#353
* gridsuite/study-server#484
* gridsuite/commons-ui#321

2023-12-06 15:52 UTC, EstherDarkish approved these changes
Code OK tests OK

2023-12-08 15:19 UTC, EstherDarkish requested changes
Doesn't work anymore : instead of the list of all the modules, we can only see gridstudy-app.

2023-12-11 09:51 UTC, flomillot commented
![image](https://github.com/gridsuite/gridstudy-app/assets/75525996/40b5453e-4f18-4968-9b32-72af5d2e3b7c)

2023-12-11 10:30 UTC, flomillot approved these changes

2023-12-11 10:45 UTC, merged