Add editable fields, new fields for spreadsheet Generator
gridsuite/gridstudy-app pull request #1757
Opened 2023-12-04 08:16 UTC by souissimai

Add and Edit new fields : 
    En compensation //  Active power control
    Réactance du transformateur // Transformer reactance
    Réactance transitoire // Transient reactance  
    P imposée //Planning P
    Indisponibilité programmée //Planning outage rate 
    Indisponibilité fortuite //Forced outage rate"
    Coût de démarrage //Startup cost
    Coefficient de participation à la compensation //Active power regulation droop
    Coefficient de participation au réglage de tension //Reactive percentage

2023-12-15 15:38 UTC, ghelloumi requested changes

2023-12-15 15:38 UTC, ghelloumi commented on src/components/spreadsheet/utils/config-tables.js
> +                },
```suggestion
                cellEditorParams: ({
                    data: {
                        activePowerControl: { activePowerControlOn = '' } = {},
                    } = {},
                    context,
                    api,
                    colDef,
                }) => {
                    return {
                        defaultValue: +activePowerControlOn,
                        gridContext: context,
                        gridApi: api,
                        colDef,
                    };
                },
```

2023-12-15 15:38 UTC, ghelloumi commented on src/components/spreadsheet/utils/config-tables.js
> +                },
```suggestion
cellEditorParams: (params) => {
                    const qPercent =
                        params.data?.coordinatedReactiveControl?.qPercent;
                    return {
                        defaultValue: isNaN(qPercent) ? 0 : qPercent,
                        gridContext: params.context,
                        gridApi: params.api,
                        colDef: params.colDef,
                    };
                },
```

2023-12-15 15:38 UTC, ghelloumi commented on src/components/spreadsheet/utils/config-tables.js
> +                        : params.data?.coordinatedReactiveControl?.qPercent,
```suggestion
valueGetter: (params) => {
                    const qPercent =
                        params.data?.coordinatedReactiveControl?.qPercent;
                    return isNaN(qPercent) ? 0 : qPercent;
                },
```

2023-12-15 16:08 UTC, AAJELLAL approved these changes

2023-12-20 10:23 UTC, AAJELLAL approved these changes

2023-12-20 13:26 UTC, ghelloumi approved these changes

2023-12-21 07:44 UTC, merged