Add spreadsheet modification for generator attributes
gridsuite/gridstudy-app pull request #1777
Opened 2023-12-12 08:24 UTC by souissimai

2023-12-13 14:59 UTC, ayolab requested changes
there is no need for this StringField

2023-12-13 14:59 UTC, ayolab commented on src/components/spreadsheet/utils/equipment-table-editors.js
> +export const StringField = forwardRef(
there is no need for this component, it has to be removed

2023-12-19 10:18 UTC, ghelloumi commented on src/components/dialogs/network-modifications/generator/modification/regulating-terminal-modification-dialog.js
> +            fetchVoltageLevelsListInfos(studyUuid, currentNode.id).then(
can you treat error case please?

2023-12-19 10:20 UTC, ghelloumi commented on src/components/dialogs/network-modifications/generator/modification/regulating-terminal-modification-dialog.js
> +            if (data.regulatingTerminalConnectableId !== ' ') {
what if `data.regulatingTerminalConnectableId === ''` or 
`data.regulatingTerminalConnectableId === '   '` (n number of white spaces)

2023-12-20 13:26 UTC, ghelloumi approved these changes

2023-12-20 14:21 UTC, AAJELLAL reviewed
I found a weird behaviour while editing the line.
After changing the the voltage level and the equipment, the chosen voltage level is assigned to **regulatingTerminalVlId** . Based on the US description the voltage level should be changed but not **regulatingTerminalVlId**. To check when the PO to be sure.

2023-12-20 14:38 UTC, AAJELLAL approved these changes

2023-12-20 14:45 UTC, souissimai commented
> I found a weird behaviour while editing the line. After changing the the voltage level and the equipment, the chosen voltage level is assigned to **regulatingTerminalVlId** . Based on the US description the voltage level should be changed but not **regulatingTerminalVlId**. To check when the PO to be sure.

we have **regulatingTerminalVlId** and **voltageLevelI** it's not the same

2023-12-21 10:31 UTC, ayolab approved these changes

2023-12-21 12:16 UTC, merged