Fixes a case where JSON.parse would try to parse undefined.
gridsuite/gridstudy-app pull request #1787
Opened 2023-12-14 13:05 UTC by EstherDarkish

2023-12-14 13:20 UTC, Mathieu-Deharbe commented on src/components/graph/menus/modification-list-item.js
> +            : {};
If {} is affected to modificationMetadata won't you have some similar trouble in the following switch ? (return modificationMetadata.lineToSplitId etc)

2023-12-14 13:43 UTC, EstherDarkish commented
This is maybe not the way to solde this issue. Changed the PR to WIP.

2023-12-14 13:48 UTC, SlimaneAmar requested changes
Message value is never null !

2023-12-15 07:55 UTC, EstherDarkish commented
Not the right way to fix the underlying issue.

2023-12-15 07:55 UTC, closed without merging