fix error when editing voltage level in line attach to vl creation
gridsuite/gridstudy-app pull request #1790
Opened 2023-12-14 14:51 UTC by YenguiSeddik

2024-01-02 09:58 UTC, ghelloumi commented on src/components/dialogs/network-modifications/line-attach-to-voltage-level/line-attach-to-voltage-level-dialog.js
> +
same code bloc in `components/dialogs/network-modifications/line-split-with-voltage-level/line-split-with-voltage-level-dialog.js` 
please find a way to create only one function.

2024-01-02 10:02 UTC, ghelloumi commented on src/components/dialogs/network-modifications/line-attach-to-voltage-level/line-attach-to-voltage-level-form.js
> +
```suggestion
    const isVoltageLevelEdit =
        voltageLevelToEdit &&
        voltageLevelToEdit.equipmentId === voltageLevelIdWatch;

```

const isVoltageLevelEdit = voltageLevelToEdit?.equipmentId === voltageLevelIdWatch;

2024-01-02 10:05 UTC, ghelloumi commented on src/components/dialogs/network-modifications/line-attach-to-voltage-level/line-attach-to-voltage-level-form.js
> +                    editData={
type of 'undefined' is not an object
but in VoltageLevelCreationDialog we have editData: PropTypes.object,

2024-01-02 10:06 UTC, ghelloumi commented on src/components/dialogs/network-modifications/line-attach-to-voltage-level/line-attach-to-voltage-level-form.js
> +                    }
type of 'undefined' is not an object
but in VoltageLevelCreationDialog we have editData: PropTypes.object,

2024-01-08 11:44 UTC, dbraquart requested changes
code: small changes requested if you agree
tests: ok (both modifications)

2024-01-09 14:24 UTC, YenguiSeddik commented on src/components/dialogs/network-modifications/line-split-with-voltage-level/line-split-with-voltage-level-dialog.js
> +                // we add the new voltage level, (or replace it if it exists). And we remove the old id if it is different (in case we modify the id)
done

2024-01-09 14:25 UTC, YenguiSeddik commented on src/components/dialogs/network-modifications/line-split-with-voltage-level/line-split-with-voltage-level-form.js
> +        if (voltageLevelIdWatch === voltageLevelToEdit?.equipmentId) {
done

2024-01-09 14:25 UTC, YenguiSeddik commented on src/components/dialogs/network-modifications/line-attach-to-voltage-level/line-attach-to-voltage-level-dialog.js
> +                newVoltageLevelOptions.push(formattedVoltageLevel);
done

2024-01-09 15:43 UTC, ayolab approved these changes

2024-01-09 17:20 UTC, dbraquart approved these changes
code: ok
tests: ok

2024-01-11 09:42 UTC, merged