[WIP] Spreadsheet substations modification
gridsuite/gridstudy-app pull request #1791
Opened 2023-12-14 15:03 UTC by ayolab

2024-01-05 16:08 UTC, AAJELLAL requested changes

2024-01-05 16:08 UTC, AAJELLAL commented on src/components/spreadsheet/utils/equipement-table-popup-editors.js
> +                return { id: index, key: key, value: data.properties[key] };
May be it's better to extract this to a single method then use it here to initiate the state.

2024-01-05 16:08 UTC, AAJELLAL commented on src/components/spreadsheet/utils/equipement-table-popup-editors.js
As a general rule new files should be in TS

2024-01-08 10:58 UTC, souissimai reviewed
At the moment of validation, the country code is shown on the country column, it seems a strange behavior

2024-01-08 15:57 UTC, jamal-khey commented
> src/components/spreadsheet/utils/equipement-table-popup-editors.js

this is fixed

2024-01-08 16:16 UTC, jamal-khey commented on src/components/spreadsheet/utils/equipement-table-popup-editors.js
> +                                        {localRowData?.map((row, index) => {
in my case key is not always unique and the user can change it. but the index is more stable

2024-01-09 14:53 UTC, AAJELLAL requested changes

2024-01-09 14:53 UTC, AAJELLAL commented on src/components/spreadsheet/utils/equipement-table-popup-editors.tsx
> +        };
You can refactor this, it's practically the same code.

2024-01-09 16:31 UTC, AAJELLAL approved these changes

2024-01-09 20:41 UTC, merged