add export csv file for LF result
gridsuite/gridstudy-app pull request #1797
Opened 2023-12-18 12:53 UTC by ghazwarhili

2023-12-21 17:12 UTC, AAJELLAL requested changes
There is a regression in voltage init. The ag-grid table is no longer visible  when I select "INDICATORS" tab and the export crashes.
To fix it you need to change    **indicatorsColumnDefs={indicatorsColumnDefs}**  to                     **columns={indicatorsColumnDefs}**.
And also check with the PO if you need to keep he headers while exporting the result or not.

2023-12-21 17:12 UTC, AAJELLAL commented on src/components/results/loadflow/load-flow-result.tsx
> +                    skipColumnHeaders={true}
Check with the PO if you need to export the header as well or not.

2023-12-21 17:12 UTC, AAJELLAL commented on src/components/results/loadflow/load-flow-result.tsx
> +                    skipColumnHeaders={true}
The same here.

2023-12-21 17:12 UTC, AAJELLAL commented on src/components/results/loadflow/load-flow-result.tsx
> +                    skipColumnHeaders={true}
The same thing here.

2023-12-26 12:21 UTC, ghelloumi commented
- Headers heights are smaller.

2023-12-26 13:36 UTC, ghelloumi requested changes

2023-12-27 08:24 UTC, ghelloumi requested changes

2023-12-27 08:24 UTC, ghelloumi commented on src/components/utils/renderTable-ExportCsv.tsx
> +}
<any, any> are not necessary

```suggestion
interface RenderTableAndExportCsvProps {
    gridRef: Ref<any> | undefined;
    columns: any[];
    defaultColDef: ColDef<any>;
    tableName: string;
    rows: any[];
    onRowDataUpdated: (event: RowDataUpdatedEvent) => void;
    headerHeight: number;
    onGridReady: ((event: GridReadyEvent) => void) | undefined;
    getRowStyle: (params: RowClassParams) => RowStyle | undefined;
    enableCellTextSelection: boolean;
    overlayNoRowsTemplate: string | undefined;
    skipColumnHeaders: boolean;
}
```

2023-12-27 08:24 UTC, ghelloumi commented on src/components/utils/renderTable-ExportCsv.tsx
> +                <Box style={{ flexGrow: 1 }}></Box>
idem, this Box is nt necessary, could you find a way to fix it please ?

2023-12-28 14:19 UTC, ghelloumi approved these changes

2023-12-28 14:26 UTC, AAJELLAL requested changes
The ag-grid table is no longer visible when I select the 3 first tabs but the  export works fine.

2023-12-28 16:01 UTC, AAJELLAL approved these changes

2023-12-28 16:16 UTC, merged