sum of reactive slacks: consumption & injection
gridsuite/gridstudy-app pull request #1829
Opened 2023-12-26 16:08 UTC by souissimai

2024-01-02 15:02 UTC, dbraquart requested changes
code: minor remarks
test: works fine, the sums are correct.

We should avoid to display many digits lile "Somme soutirage  2150.9800000000005"

2024-01-02 15:10 UTC, AAJELLAL requested changes

2024-01-02 15:10 UTC, AAJELLAL commented on src/components/voltage-init-result.js
> +                        <Typography style={{ fontWeight: 'bold' }}>
move this to the **styles** object instead of hardcoding it here.

2024-01-02 15:10 UTC, AAJELLAL commented on src/components/voltage-init-result.js
> +                            {totalConsumption}
The same thing here.

2024-01-02 15:10 UTC, AAJELLAL commented on src/components/voltage-init-result.js
> +            : 0;
You can do more refactoring here.
You are practically using the same code to get totalInjection and totalConsumption.

2024-01-03 13:05 UTC, dbraquart requested changes
code: a small change to make
tests: ok

2024-01-03 13:05 UTC, dbraquart commented on src/components/voltage-init-result.js
> +            resultToShow.reactiveSlacks,
you have to pass the function param "reactiveSlacks" here instead of "resultToShow.reactiveSlacks".
otherwise the function param is useless.

2024-01-03 13:05 UTC, dbraquart commented on src/components/voltage-init-result.js
> +            resultToShow.reactiveSlacks,
same here

2024-01-03 13:21 UTC, dbraquart approved these changes

2024-01-03 13:31 UTC, AAJELLAL approved these changes

2024-01-04 09:36 UTC, merged