Homogenize load attributes
gridsuite/gridstudy-app pull request #1862
Opened 2024-01-12 13:14 UTC by souissimai

2024-01-17 09:51 UTC, SlimaneAmar approved these changes

2024-01-23 16:40 UTC, Mathieu-Deharbe requested changes

2024-01-23 16:40 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/load/modification/load-modification-dialog.js
> +            console.log('mooo ', load);
Forgotten log ?

2024-01-23 16:40 UTC, Mathieu-Deharbe commented on src/translations/fr.json
> +    "q0": "P constant (MW)",
You have switched the units : p0 should be in MW and q0 in MVar.

2024-01-24 12:58 UTC, souissimai commented on src/components/dialogs/network-modifications/load/modification/load-modification-dialog.js
> +            console.log('mooo ', load);
yes

2024-01-24 15:16 UTC, Mathieu-Deharbe approved these changes

2024-01-24 15:28 UTC, merged