Add busbar sections to spreadsheet
gridsuite/gridstudy-app pull request #1926
Opened 2024-02-15 18:07 UTC by Meklo

2024-02-16 10:17 UTC, Meklo commented
French locales may be temporary

2024-02-16 13:05 UTC, FranckLecuyer requested changes

2024-02-16 13:05 UTC, FranckLecuyer commented on src/components/spreadsheet/utils/config-tables.js
> +        type: EQUIPMENT_TYPES.BUSBAR_SECTION,
BUS instead of BUSBAR_SECTION
see remarks in  PR : https://github.com/gridsuite/network-map-server/pull/160

2024-02-19 16:16 UTC, dbraquart requested changes
code: ok
tests: I made a CR (to be confirmed) because:
- header names should be plural (ex: Buses)
- we can filter only on voltage magnitude/angle columns, not the others

2024-02-20 12:21 UTC, FranckLecuyer requested changes

2024-02-20 12:21 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "ConnectedComponent": "Composant connecté",
"Composante connexe"

2024-02-20 12:21 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "SynchronousComponent": "Composant synchrone",
"Composante synchrone"

2024-02-20 12:21 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "Magnitude": "Amplitude de la tension",
"Tension"

2024-02-20 12:21 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "Magnitude": "Amplitude de la tension",
"Tension"

2024-02-20 12:21 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "Angle": "Angle de la tension",
"Phase"

2024-02-20 14:28 UTC, FranckLecuyer approved these changes

2024-02-20 14:39 UTC, dbraquart approved these changes

2024-02-20 15:31 UTC, merged