use message for updating looadflowbutton state
gridsuite/gridstudy-app pull request #195
Opened 2020-09-17 07:48 UTC by JacquesBorsenberger

Signed-off-by: jacqbors <jacques.borsenberger@rte-france.com>

# Conflicts:
#	src/components/study-pane.js

2020-09-18 09:40 UTC, ChamseddineBhd requested changes

2020-09-18 09:40 UTC, ChamseddineBhd commented on src/components/study-pane.js
> +    const [loadFlowRunning, setLoadFlowRunning] = useState(LFStatus.NOT_RUN);
loadFlowState ?

2020-09-18 09:49 UTC, JacquesBorsenberger commented on src/components/study-pane.js
> +        NOT_RUN: 'Start LoadFlow',
it's the initial state, when the loadflow has not been run, CONVERGED & DIVERGED are also 'not running'

2020-09-18 11:29 UTC, JacquesBorsenberger commented on src/components/study-pane.js
> +    const [loadFlowRunning, setLoadFlowRunning] = useState(LFStatus.NOT_RUN);
done

2020-10-02 08:42 UTC, ChamseddineBhd approved these changes

2020-10-03 16:17 UTC, mikatheo requested changes
Really nice!
It works rather well, however I have 2 remarks:
- When the Loadflow is finished, the network image loses the voltage level selection (all are displayed)
- The colors grey / green / red / orange make it difficult to distinguish the label, could the contrast between the two be enhanced?

2020-10-06 18:50 UTC, geofjamg approved these changes

2020-10-06 18:51 UTC, merged