Add property column and handle its editing for all spreadsheet equipments.
gridsuite/gridstudy-app pull request #2012
Opened 2024-03-18 14:38 UTC by AAJELLAL

2024-03-20 13:10 UTC, ayolab requested changes
Tests OK
Code OK with minor requested changes

2024-03-20 13:10 UTC, ayolab commented on src/components/spreadsheet/utils/config-tables.js
> +                //  editable: isEditable,
Please remove these comments

2024-03-20 13:10 UTC, ayolab commented on src/components/spreadsheet/utils/config-tables.js
> +                // editable: isEditable,
same here

2024-03-20 13:10 UTC, ayolab commented on src/components/spreadsheet/utils/config-tables.js
> +                //   editable: isEditable,
same here

2024-03-20 13:10 UTC, ayolab commented on src/components/spreadsheet/utils/config-tables.js
> +                //  editable: isEditable,
same here

2024-03-20 13:10 UTC, ayolab commented on src/components/spreadsheet/utils/config-tables.js
> +                //  editable: isEditable,
same here

2024-03-20 13:10 UTC, ayolab commented on src/components/spreadsheet/utils/config-tables.js
> +                // editable: isEditable,
same here

2024-03-20 13:10 UTC, ayolab commented on src/components/spreadsheet/utils/config-tables.js
> +                cellEditor: SitePropertiesEditor,
can you please rename the cellEditor to `PropertiesEditor` since now it is used for all equipments

2024-03-21 10:38 UTC, ayolab approved these changes

2024-03-21 11:01 UTC, souissimai approved these changes

2024-03-21 14:04 UTC, merged