feat(voltage-init-parameters): add a new general tab
gridsuite/gridstudy-app pull request #2028
Opened 2024-03-25 15:46 UTC by TheMaskedTurtle

Add a new Tab for general parameters in voltage init parameters

2024-04-03 11:33 UTC, FranckLecuyer requested changes

2024-04-03 11:33 UTC, FranckLecuyer commented on src/components/dialogs/parameters/voltageinit/use-get-voltage-init-parameters.tsx
> +import { VoltageInitParam } from './voltage-init-utils';
Missing license header

2024-04-03 11:33 UTC, FranckLecuyer commented on src/components/dialogs/parameters/voltageinit/voltage-init-parameters-form.tsx
> +import yup from '../../../utils/yup-config';
Missing license header

2024-04-03 11:35 UTC, FranckLecuyer requested changes
Tests: OK

2024-04-03 13:43 UTC, TheMaskedTurtle commented on src/components/dialogs/parameters/voltageinit/use-get-voltage-init-parameters.tsx
> +import { VoltageInitParam } from './voltage-init-utils';
Fixed

2024-04-04 07:22 UTC, FranckLecuyer approved these changes

2024-04-05 14:34 UTC, merged