Update server port to 3002
gridsuite/gridstudy-app pull request #2035
Opened 2024-03-28 14:18 UTC by flomillot

2024-03-28 15:08 UTC, Tristan-WorkGH requested changes

2024-03-28 15:08 UTC, Tristan-WorkGH commented on public/idpSettings.json
> +    "silent_redirect_uri": "http://localhost:3002/silent-renew-callback",
```suggestion
    "redirect_uri": "http://localhost:3004/sign-in-callback",
    "post_logout_redirect_uri": "http://localhost:3004/logout-callback",
    "silent_redirect_uri": "http://localhost:3004/silent-renew-callback",
```

2024-03-28 15:08 UTC, Tristan-WorkGH commented on vite.config.ts
> +    port: 3002,
```suggestion
    port: 3004,
```

2024-03-28 17:24 UTC, Tristan-WorkGH approved these changes

2024-03-29 08:28 UTC, EstherDarkish approved these changes

2024-04-02 10:50 UTC, merged