Exclude bus equipment from list of equipments
gridsuite/gridstudy-app pull request #2071
Opened 2024-04-25 08:19 UTC by souissimai

2024-05-03 11:33 UTC, antoinebhs requested changes
Exclude HVDC Converter Station and Tie line too

2024-05-03 11:59 UTC, antoinebhs commented on src/components/network/filter-creation-panel.tsx
> +                                        !type.includes(EQUIPMENT_TYPES.BUS) &&
Maybe we can create a Set of equipmentTypesToExclude

2024-05-06 07:44 UTC, jamal-khey approved these changes

2024-05-13 08:10 UTC, antoinebhs approved these changes
Code OK
Tests OK

2024-05-13 09:36 UTC, merged