Fix select provider in paramaters
gridsuite/gridstudy-app pull request #2105
Opened 2024-05-30 12:33 UTC by achour94

To fix the autocomplete render issues in the Edge browser, we have replaced it with a simple MUI Select component provided by commons-ui.

2024-05-31 06:45 UTC, ayolab requested changes
The problem is still present on "Generation kind" fields in "non-evacuated energy" parameters, "Sensitivity type" and "Distribution type" in "sensitivity analysis" parameters.
And by the way there is "DropDown" component that is used in "Dynamic simulation" parameters for the same purpose, I think that we should either reuse it or replace it with the MuiSelectInput

2024-06-03 12:32 UTC, achour94 commented
> The problem is still present on "Generation kind" fields in "non-evacuated energy" parameters, "Sensitivity type" and "Distribution type" in "sensitivity analysis" parameters. And by the way there is "DropDown" component that is used in "Dynamic simulation" parameters for the same purpose, I think that we should either reuse it or replace it with the MuiSelectInput

Thank you for noticing, i resolve the mentionned issues and another one related to 'Solver type' in 'Dynamic simulation'.
Regarding 'DropDown', its a component not connected to react hook form.

2024-06-03 13:15 UTC, ayolab approved these changes

2024-06-04 15:20 UTC, anistouri approved these changes

2024-06-05 07:22 UTC, merged