refactor: simplify data mapping for reports
gridsuite/gridstudy-app pull request #2227
Opened 2024-08-28 10:56 UTC by TheMaskedTurtle

2024-08-29 17:12 UTC, dbraquart requested changes
code : a few remarks
tests: 1 test case ko
- in incremental built, severity is not set at the node level

2024-08-30 09:23 UTC, TheMaskedTurtle commented on src/utils/report-tree.mapper.ts
> +    const severityList = report.severities || report.subReports.flatMap((subReport) => subReport.severities);
I still need this one, only for one case, to evaluate severities for "Logs" container

2024-08-30 10:02 UTC, TheMaskedTurtle commented on src/components/report-viewer/report-viewer.jsx
> +export default function ReportViewer({ report, reportType, maxSubReports = MAX_SUB_REPORTS }) {
done

2024-08-30 10:03 UTC, TheMaskedTurtle commented on src/components/results/common/computation-report-viewer.tsx
> +    const { snackError } = useSnackMessage();
weird this was not linted for me :thinking:

2024-08-30 10:03 UTC, TheMaskedTurtle commented on src/hooks/use-report-fetcher.tsx
> +    if (report.message !== 'Root') {
created a new constant file as it is more related to nodes

2024-08-30 14:41 UTC, dbraquart commented on src/utils/report-tree.mapper.ts
> +    const severityList = report.severities || report.subReports.flatMap((subReport) => subReport.severities);
ok!

2024-08-30 14:41 UTC, dbraquart commented on src/components/results/common/computation-report-viewer.tsx
> +    const { snackError } = useSnackMessage();
me neither, I just noticed

2024-09-03 14:59 UTC, merged