edit access rights of study after creation
gridsuite/gridstudy-app pull request #226
Opened 2020-10-16 22:46 UTC by AbdelHedhili

Signed-off-by: AbdelHedhili <abdelsalem.hedhili@rte-france.com>

2020-10-18 13:42 UTC, geofjamg requested changes
See comments

2020-10-18 13:42 UTC, geofjamg commented on src/utils/rest-api.js
> +        PREFIX_STUDY_QUERIES +
Thre is a new getStudyUrl() to share this little piece of code. Could you use it?

2020-10-18 13:42 UTC, geofjamg commented on src/utils/dialogs.js
> +const AccessRightsDialog = ({
dialogs.js is not dedicated to receive all dialogs of the app. Is was just supposed to get very generic and reusable dialogs like "rename". Could you create a access-rights-dialog.js for that?

2020-10-19 21:15 UTC, geofjamg requested changes
- public to private works
- private to public doesn't work => to fix
- are we allowed to switch public to private when we don't own the study? I think we should not.
- when we switch private to study we should fire an study list update event sot that all other navigators update (here you do it synchronously which was the old way to do it)

2020-10-20 10:07 UTC, AbdelHedhili commented
>     * are we allowed to switch public to private when we don't own the study? I think we should not.
> 
>     * when we switch private to study we should fire an study list update event sot that all other navigators update (here you do it synchronously which was the old way to do it)
 
I confirm we can't change the rights on a study we don't own.

2020-10-20 11:50 UTC, SlimaneAmar commented on src/components/access-rights-dialog.js
> +};
Why don't we use the plain object study as a property ?

2020-10-20 13:42 UTC, SlimaneAmar approved these changes

2020-10-20 16:27 UTC, geofjamg approved these changes

2020-10-20 16:27 UTC, merged