Fix invalid hook call while using flux convention
gridsuite/gridstudy-app pull request #2338
Opened 2024-10-21 16:12 UTC by dbraquart

2024-10-22 11:39 UTC, FranckLecuyer requested changes
Tests: the filter 'not equal' does not apply correctly : it is equivalent to 'greater than or equal to' ...

2024-10-24 15:25 UTC, FranckLecuyer requested changes
Tests: NOK

2024-10-25 12:19 UTC, ayolab approved these changes
Tests : OK

2024-10-25 12:33 UTC, FranckLecuyer approved these changes

2024-10-25 12:41 UTC, merged