fix for conversion micro unit in spreadsheet
gridsuite/gridstudy-app pull request #2353
Opened 2024-10-25 10:32 UTC by ghazwarhili

2024-10-30 09:19 UTC, etiennehomer requested changes
In the equipments spreadshit, the susceptance is in μS. So it's normal to use unitToMicroUnit() to convert them. The problem is that for modification by formula and modication by filter, the susceptance value is taken as Siemens, not μSiemens

2024-11-05 14:15 UTC, etiennehomer requested changes

2024-11-05 14:15 UTC, etiennehomer commented on src/components/dialogs/network-modifications/by-filter/by-assignment/assignment/assignment-constants.ts
> +        unit: MICRO_SIEMENS,
Ohm for resistance ! Do not change here

2024-11-05 15:04 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/by-filter/by-assignment/assignment/assignment-constants.ts
> +        unit: MICRO_SIEMENS,
good catch !

2024-11-05 16:02 UTC, etiennehomer requested changes

2024-11-05 16:02 UTC, etiennehomer commented on src/components/dialogs/network-modifications/by-filter/by-assignment/assignment/assignment-constants.ts
> +        outputConverter: (value) => unitToKiloUnit(value),
Conversion doesn't work for short circuit current limit for me

2024-11-05 16:07 UTC, etiennehomer requested changes

2024-11-05 16:07 UTC, etiennehomer commented on src/components/dialogs/network-modifications/by-filter/by-assignment/assignment/assignment-constants.ts
> +        outputConverter: (value) => unitToKiloUnit(value),
To inverse

2024-11-05 16:14 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/by-filter/by-assignment/assignment/assignment-utils.ts
> +export const getFieldOptionType = (fieldName?: string | null) => {
done

2024-11-05 16:14 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/by-filter/by-assignment/assignment/assignment-utils.ts
> +type FieldValue = string | number | boolean;
done

2024-11-06 10:27 UTC, etiennehomer commented on src/components/dialogs/network-modifications/by-filter/by-assignment/modification-by-assignment-dialog.tsx
> +                assignment[VALUE_FIELD] = Number(valueConverted);
Add the VALUE_FIELD in the return to be homogeneous with the useEffet() above.

2024-11-06 10:35 UTC, etiennehomer commented on src/components/dialogs/network-modifications/by-filter/by-assignment/modification-by-assignment-dialog.tsx
> +                assignment[VALUE_FIELD] = Number(valueConverted);
And remove Number()

2024-11-06 10:43 UTC, etiennehomer approved these changes

2024-11-06 11:03 UTC, merged