creation line full width interface
gridsuite/gridstudy-app pull request #2390
Opened 2024-11-13 12:49 UTC by Mathieu-Deharbe

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +    selectedLimitGroup1,
selectedLimit**s**Group1 (to align with the naming on the back)

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +    selectedLimitGroup2,
selectedLimitsGroup2

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +    selectedLimitGroup1,
selectedLimitsGroup1

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +    selectedLimitGroup2,
selectedLimitsGroup2

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +    limitsGroups1,
limitsGroup1

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +    limitsGroups2,
limitsGroup2

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +    limitsGroups1,
limitsGroup1

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +    limitsGroups2,
limitsGroup2

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +            [LIMITS_GROUP_1]: limitsGroups1,
use camelCase for variable names operationalLimitsGroups1

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +            [LIMITS_GROUP_2]: limitsGroups2,
the same here

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/network-modification-types.ts
> +    limitsGroups1: OperationalLimitsGroup[];
limitsGroup1

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/network-modification-types.ts
> +    limitsGroups2: OperationalLimitsGroup[];
limitsGroup2

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/network-modification-types.ts
> +    limitsGroups1: OperationalLimitsGroup[];
limitsGroup1

2025-01-08 18:59 UTC, ghazwarhili commented on src/services/network-modification-types.ts
> +    limitsGroups2: OperationalLimitsGroup[];
limitsGroup2

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/utils/field-constants.ts
> +export const LIMITS_GROUP_1 = 'operationalLimitsGroups1';
operationalLimitsGroup1

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/utils/field-constants.ts
> +export const LIMITS_GROUP_2 = 'operationalLimitsGroups2';
operationalLimitsGroup2

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/selected-operational-limit-group.tsx
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
2025

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-type.ts
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
2025

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane.tsx
> +}
It's a large file .. we absolutely need to refactor it

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +              )
Or just
```
temporaryLimitList?.filter(
        (limit) => limit?.name?.trim()) )
```

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +        : [];
```suggestion
        || [];
```

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +        ? temporaryLimitList
```
temporaryLimitList?.filter(
```

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +export const sanitizeLimitsGroups = (limitsGroups /*: OperationalLimitsGroup[]*/) =>
```
/**
 * Sanitize and filter operational limits group
 */
export const sanitizeLimitsGroups = (limitsGroups /*: OperationalLimitsGroup[]*/) =>
```

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +                    (limit) =>
```
.filter(({ name }) => name?.trim())
```

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +          };
to make this function more clear and avoid duplication 
I suggest to create currentLimits and limitsGroup variables 
```
const currentLimits = {
        [CURRENT_LIMITS_1]: {
            [PERMANENT_LIMIT]: null,
            [TEMPORARY_LIMITS]: [],
        },
        [CURRENT_LIMITS_2]: {
            [PERMANENT_LIMIT]: null,
            [TEMPORARY_LIMITS]: [],
        },
    };

    const limitsGroup = {
        [LIMITS_GROUP_1]: [],
        [LIMITS_GROUP_2]: [],
        [SELECTED_LIMITS_GROUP_1]: null,
        [SELECTED_LIMITS_GROUP_2]: null,
    };
```
and then the resturn 

```
 return {   [id]: onlySelectedLimits ? currentLimits : limitsGroup,  };
```

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +          };
you can use this approach to structure the schema dynamically 

```
const currentLimitsSchema = {
    [CURRENT_LIMITS_1]: yup.object().shape(currentLimitsValidationSchema()),
    [CURRENT_LIMITS_2]: yup.object().shape(currentLimitsValidationSchema()),
  };

  const limitsGroupSchema = {
    [LIMITS_GROUP_1]: yup.array(yup.object().shape(limitsGroupValidationSchema())),
    [LIMITS_GROUP_2]: yup.array(yup.object().shape(limitsGroupValidationSchema())),
    [SELECTED_LIMITS_GROUP_1]: yup.string().nullable(),
    [SELECTED_LIMITS_GROUP_2]: yup.string().nullable(),
  };

  return {
    [id]: yup.object().shape(onlySelectedLimits ? currentLimitsSchema : limitsGroupSchema),
   };
```

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +        }), */
It's an oversight?

2025-01-08 18:59 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +                });
or maybe you can extract the createLimitSchema with isRequired argument it makes the TEMPORARY_LIMIT_NAME field required
```
const createLimitSchema = (isRequired = false) => {
  return yup.object().shape({
    [TEMPORARY_LIMIT_NAME]: yup.string().nullable().required(isRequired),
    [TEMPORARY_LIMIT_DURATION]: yup.number().nullable().min(0),
    [TEMPORARY_LIMIT_VALUE]: yup.number().nullable().positive(),
  });
};
```
and then you can do the call 

```
yup.lazy((item) => {
  return item[TEMPORARY_LIMIT_NAME]
    ? createLimitSchema(true) 
    : createLimitSchema(); 
});
```

2025-01-09 08:28 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane.tsx
> +                    </Tabs>
it could be extracted in another component (to handle the tabs)

2025-01-09 11:28 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane-utils.js
> +                });
It looks like the parameter of `required` is a message, not a boolean. But I did a refactoring similar to what you proposed : `temporaryLimitsValidationSchema`.

2025-01-09 11:29 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane-utils.js
> +        }), */
Actually I didn't know how to do it yet. Now it is done.

2025-01-09 11:52 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane-utils.js
> +          };
Indeed this will be easier to read. Done.

2025-01-09 11:52 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane-utils.js
> +          };
Indeed this will be easier to read. Done.

2025-01-09 11:52 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane-utils.js
> +export const sanitizeLimitsGroups = (limitsGroups /*: OperationalLimitsGroup[]*/) =>
Changed into `sanitizes limit names and filters out the empty temporary limits lines`.

2025-01-09 11:52 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane.tsx
> + * Copyright (c) 2023, RTE (http://www.rte-france.com)
I turned that file into typescript and changed it massively but didn't create it. I also refactored it a lot and created  limits-side-pane.tsx

Github seems confused by the refactoring.

2025-01-09 13:59 UTC, Mathieu-Deharbe commented on src/services/network-modification-types.ts
> +    limitsGroups1: OperationalLimitsGroup[];
This is an array of `OperationalLimitsGroup` so I think that the 's' makes more sense.

2025-01-09 13:59 UTC, Mathieu-Deharbe commented on src/services/network-modification-types.ts
> +    limitsGroups2: OperationalLimitsGroup[];
This is an array of `OperationalLimitsGroup` so I think that the 's' makes more sense.

2025-01-09 14:01 UTC, Mathieu-Deharbe commented on src/services/network-modification-types.ts
> +    limitsGroups2: OperationalLimitsGroup[];
This is an array of OperationalLimitsGroup so I think that the 's' makes more sense.

2025-01-09 14:01 UTC, Mathieu-Deharbe commented on src/services/study/network-modifications.ts
> +    limitsGroups1,
This is an array of OperationalLimitsGroup so I think that the 's' makes more sense.

2025-01-09 14:01 UTC, Mathieu-Deharbe commented on src/services/study/network-modifications.ts
> +    limitsGroups2,
This is an array of OperationalLimitsGroup so I think that the 's' makes more sense.

2025-01-09 14:19 UTC, Mathieu-Deharbe commented on src/services/study/network-modifications.ts
> +    selectedLimitGroup1,
Done.

2025-01-09 14:19 UTC, Mathieu-Deharbe commented on src/services/study/network-modifications.ts
> +    selectedLimitGroup2,
Done.

2025-01-09 14:19 UTC, Mathieu-Deharbe commented on src/services/study/network-modifications.ts
> +    selectedLimitGroup1,
Done.

2025-01-09 14:19 UTC, Mathieu-Deharbe commented on src/services/study/network-modifications.ts
> +    selectedLimitGroup2,
Done.

2025-01-09 14:19 UTC, Mathieu-Deharbe commented on src/services/study/network-modifications.ts
> +    limitsGroups1,
This is an array of OperationalLimitsGroup so I think that the 's' makes more sense.

2025-01-09 14:19 UTC, Mathieu-Deharbe commented on src/services/study/network-modifications.ts
> +    limitsGroups2,
This is an array of OperationalLimitsGroup so I think that the 's' makes more sense.

2025-01-09 14:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane.tsx
> +            </Grid>
Done.

2025-01-09 14:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane.tsx
> +        </Grid>
Much better indeed. Done.

2025-01-13 14:56 UTC, Mathieu-Deharbe commented
> second problem i see active limit sets seems to be mandatory even if marked optional
> 
> ![Capture d’écran du 2025-01-10 16-59-11](https://private-user-images.githubusercontent.com/178886530/402071311-b31b6b79-8d97-4900-a3e3-7a591754e6bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NTk0NTYsIm5iZiI6MTczNjc1OTE1NiwicGF0aCI6Ii8xNzg4ODY1MzAvNDAyMDcxMzExLWIzMWI2Yjc5LThkOTctNDkwMC1hM2UzLTdhNTkxNzU0ZTZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExM1QwOTA1NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmMzM2E3N2FiMDFlZDhlNDFiNWIxYTAxMzdmNTkwYzgxYjk4MzgzYmRlYjczYzA0NmZlYzAyZmEwMWMxNWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T5_JpsWGLD9OQ1N4f7i1hBGF-BVDfPVecb6Jrhe_inI)

2025-01-21 10:27 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane.tsx
> +                    </Tabs>
Done. To `operational-limits-groups-tabs.jsx`.

2025-01-29 10:27 UTC, basseche commented
i have an issue on focus on fields side 2, when i try to modify a value i lose focus each time i hit a key :

![perteFocus](https://github.com/user-attachments/assets/d798cdad-c0f5-41ac-b324-10e32d429aaa)

2025-01-29 10:51 UTC, basseche commented
The way we index name of duplicated limitset is strange : 

here i duplicate duplicated limit sets : 
![Capture d’écran du 2025-01-29 11-47-51](https://github.com/user-attachments/assets/cec29b0b-56a6-489b-bc0e-e8cc31b82d6b)

duplicate limit set when we have another limitSet : 
![Capture d’écran du 2025-01-29 11-49-06](https://github.com/user-attachments/assets/4f5085ab-da45-450c-bab2-a718f16873e5)

![Capture d’écran du 2025-01-29 11-49-36](https://github.com/user-attachments/assets/3a3163f2-3125-4b60-95dd-027e89928573)

2025-01-29 10:56 UTC, basseche commented
when i open the dialog no Limit set is selected, i think you should select active one : 
 
![Capture d’écran du 2025-01-29 11-55-31](https://github.com/user-attachments/assets/0f7080e3-f96f-46fb-9d71-36ee10205901)

2025-01-29 11:02 UTC, basseche commented
When i open the tab of limit sets the selected limit set is not necessarly the active one !

![Capture d’écran du 2025-01-29 12-00-17](https://github.com/user-attachments/assets/3b944b42-495d-4ab6-ba16-ed5082f931b7)

2025-01-29 11:06 UTC, basseche commented
i can create a limit set with a blank name, the dialog indicates that there is a mistake but doesn't really indicates what is wrong

![Capture d’écran du 2025-01-29 12-05-30](https://github.com/user-attachments/assets/0b4b2252-8061-49de-8bd4-a70509e64053)

2025-01-29 11:31 UTC, Mathieu-Deharbe commented
> When i open the tab of limit sets the selected limit set is not necessarly the active one !
> 
> ![Capture d’écran du 2025-01-29 12-00-17](https://private-user-images.githubusercontent.com/178886530/407704838-3b944b42-495d-4ab6-ba16-ed5082f931b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNTA0MzYsIm5iZiI6MTczODE1MDEzNiwicGF0aCI6Ii8xNzg4ODY1MzAvNDA3NzA0ODM4LTNiOTQ0YjQyLTQ5NWQtNGFiNi1iYTE2LWVkNTA4MmY5MzFiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyOVQxMTI4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjE3NTY2N2JkMjdlMDA1MGE1ZDU4ZjU0NzY1M2U4MWFjMDY4MzVmMTJmM2Q3Y2QzNWFjYWQ3MTA2MzM3YTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IeCDn6c_03EBviYM1boKEqfVeYJRbkeixWKiyybjrGo)

This is on purpose : it is literally impossible to select the active ones because they may be different from each other (side 1 and side 2).

Tab selection and active limit set are completely dissociated.

2025-01-29 12:59 UTC, basseche commented
> > When i open the tab of limit sets the selected limit set is not necessarly the active one !
> > ![Capture d’écran du 2025-01-29 12-00-17](https://private-user-images.githubusercontent.com/178886530/407704838-3b944b42-495d-4ab6-ba16-ed5082f931b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNTA0MzYsIm5iZiI6MTczODE1MDEzNiwicGF0aCI6Ii8xNzg4ODY1MzAvNDA3NzA0ODM4LTNiOTQ0YjQyLTQ5NWQtNGFiNi1iYTE2LWVkNTA4MmY5MzFiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyOVQxMTI4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjE3NTY2N2JkMjdlMDA1MGE1ZDU4ZjU0NzY1M2U4MWFjMDY4MzVmMTJmM2Q3Y2QzNWFjYWQ3MTA2MzM3YTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IeCDn6c_03EBviYM1boKEqfVeYJRbkeixWKiyybjrGo)
> 
> This is on purpose : it is literally impossible to select the active ones because they may be different from each other (side 1 and side 2).
> 
> Tab selection and active limit set are completely dissociated.

I understand, but when it is the same limitSet we should be able to do it. No ?

2025-01-29 13:11 UTC, basseche commented
when we create a line by copy and data is already present in formula, We should ask for confirmation before overriding data (in the specs). Actually, it is not what happens.

![copieWithoutConfirmation](https://github.com/user-attachments/assets/80da7975-41a8-42e7-b167-f6236be0b515)

2025-01-29 13:27 UTC, Mathieu-Deharbe commented
> > > When i open the tab of limit sets the selected limit set is not necessarly the active one !
> > > ![Capture d’écran du 2025-01-29 12-00-17](https://private-user-images.githubusercontent.com/178886530/407704838-3b944b42-495d-4ab6-ba16-ed5082f931b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNTA0MzYsIm5iZiI6MTczODE1MDEzNiwicGF0aCI6Ii8xNzg4ODY1MzAvNDA3NzA0ODM4LTNiOTQ0YjQyLTQ5NWQtNGFiNi1iYTE2LWVkNTA4MmY5MzFiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyOVQxMTI4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjE3NTY2N2JkMjdlMDA1MGE1ZDU4ZjU0NzY1M2U4MWFjMDY4MzVmMTJmM2Q3Y2QzNWFjYWQ3MTA2MzM3YTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IeCDn6c_03EBviYM1boKEqfVeYJRbkeixWKiyybjrGo)
> > 
> > 
> > This is on purpose : it is literally impossible to select the active ones because they may be different from each other (side 1 and side 2).
> > Tab selection and active limit set are completely dissociated.
> 
> I understand, but when it is the same limitSet we should be able to do it. No ?

If Thibault asks for it ok. 

Only when opening or also when the user changed the selected limit set to be the same on both side ? And what if they are different ? Only the side one ? Or none ?

2025-01-29 13:39 UTC, basseche commented
> > > > When i open the tab of limit sets the selected limit set is not necessarly the active one !
> > > > ![Capture d’écran du 2025-01-29 12-00-17](https://private-user-images.githubusercontent.com/178886530/407704838-3b944b42-495d-4ab6-ba16-ed5082f931b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNTA0MzYsIm5iZiI6MTczODE1MDEzNiwicGF0aCI6Ii8xNzg4ODY1MzAvNDA3NzA0ODM4LTNiOTQ0YjQyLTQ5NWQtNGFiNi1iYTE2LWVkNTA4MmY5MzFiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyOVQxMTI4NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjE3NTY2N2JkMjdlMDA1MGE1ZDU4ZjU0NzY1M2U4MWFjMDY4MzVmMTJmM2Q3Y2QzNWFjYWQ3MTA2MzM3YTJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.IeCDn6c_03EBviYM1boKEqfVeYJRbkeixWKiyybjrGo)
> > > 
> > > 
> > > This is on purpose : it is literally impossible to select the active ones because they may be different from each other (side 1 and side 2).
> > > Tab selection and active limit set are completely dissociated.
> > 
> > 
> > I understand, but when it is the same limitSet we should be able to do it. No ?
> 
> Technically ye. If Thibault asks for it ok.
> 
> Only when opening or also when the user changed the selected limit set to be the same on both side ? And what if they are different ? Only the side one ? Or none ?

I will mark it as resolve. Thibault said we will do it after.

2025-01-29 14:13 UTC, basseche commented
- Create a new line
- Copy another line
- Go to edit limit sets => no limit set selected 

![Capture d’écran du 2025-01-29 15-11-57](https://github.com/user-attachments/assets/74a8f313-860b-4798-8cb1-60026d10c3cb)

2025-01-29 15:12 UTC, Mathieu-Deharbe commented
> i have an issue on focus on fields side 2, when i try to modify a value i lose focus each time i hit a key :
> 
> ![perteFocus](https://private-user-images.githubusercontent.com/178886530/407693289-d798cdad-c0f5-41ac-b324-10e32d429aaa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNjM2MjMsIm5iZiI6MTczODE2MzMyMywicGF0aCI6Ii8xNzg4ODY1MzAvNDA3NjkzMjg5LWQ3OThjZGFkLWMwZjUtNDFhYy1iMzI0LTEwZTMyZDQyOWFhYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyOVQxNTA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2ExMjhkNWFjYjI5NzZmNzEyMDI0NmJhODFhOTBmMjdiNDBhNDFkMjg2MWU5ODNmOTlmYTE1YmI2NDRkY2JmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kFwAteaXD_eub-mZefPj42why23ZfEh5470DI_j3mLs) [ ![perteFocus](https://private-user-images.githubusercontent.com/178886530/407693289-d798cdad-c0f5-41ac-b324-10e32d429aaa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNjM2MjMsIm5iZiI6MTczODE2MzMyMywicGF0aCI6Ii8xNzg4ODY1MzAvNDA3NjkzMjg5LWQ3OThjZGFkLWMwZjUtNDFhYy1iMzI0LTEwZTMyZDQyOWFhYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyOVQxNTA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2ExMjhkNWFjYjI5NzZmNzEyMDI0NmJhODFhOTBmMjdiNDBhNDFkMjg2MWU5ODNmOTlmYTE1YmI2NDRkY2JmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kFwAteaXD_eub-mZefPj42why23ZfEh5470DI_j3mLs) ](https://private-user-images.githubusercontent.com/178886530/407693289-d798cdad-c0f5-41ac-b324-10e32d429aaa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNjM2MjMsIm5iZiI6MTczODE2MzMyMywicGF0aCI6Ii8xNzg4ODY1MzAvNDA3NjkzMjg5LWQ3OThjZGFkLWMwZjUtNDFhYy1iMzI0LTEwZTMyZDQyOWFhYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyOVQxNTA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2ExMjhkNWFjYjI5NzZmNzEyMDI0NmJhODFhOTBmMjdiNDBhNDFkMjg2MWU5ODNmOTlmYTE1YmI2NDRkY2JmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kFwAteaXD_eub-mZefPj42why23ZfEh5470DI_j3mLs) [ ](https://private-user-images.githubusercontent.com/178886530/407693289-d798cdad-c0f5-41ac-b324-10e32d429aaa.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNjM2MjMsIm5iZiI6MTczODE2MzMyMywicGF0aCI6Ii8xNzg4ODY1MzAvNDA3NjkzMjg5LWQ3OThjZGFkLWMwZjUtNDFhYy1iMzI0LTEwZTMyZDQyOWFhYS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyOVQxNTA4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00N2ExMjhkNWFjYjI5NzZmNzEyMDI0NmJhODFhOTBmMjdiNDBhNDFkMjg2MWU5ODNmOTlmYTE1YmI2NDRkY2JmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kFwAteaXD_eub-mZefPj42why23ZfEh5470DI_j3mLs)

Well seen ! Corrected but I had to remove my refresh trick, so the << >> needs reworking. I am on it.

2025-01-29 17:05 UTC, Mathieu-Deharbe commented
> Limits set names should be unique !
> 
> ![Capture d’écran du 2025-01-29 11-39-17](https://private-user-images.githubusercontent.com/178886530/407697894-71cf69de-1905-405f-b6be-f7c63d87d28a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgxNjQyNjEsIm5iZiI6MTczODE2Mzk2MSwicGF0aCI6Ii8xNzg4ODY1MzAvNDA3Njk3ODk0LTcxY2Y2OWRlLTE5MDUtNDA1Zi1iNmJlLWY3YzYzZDg3ZDI4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEyOVQxNTE5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZGJhYTFiZjRmZTkxN2ZkMGI1NDlkNDdlMThhYmE0MjJkOTAyOTFmZTVhYmQwZmUyYWQ3YmE0MjVhZDk4NzRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qKE5sx6e2Dh5elHaD7iHSlqyihhseWEUv1XiGNOJt6s)
> 
> when i do so and modify one set all sets will be modified

Added a limit set naming control with error messages : 

![image](https://github.com/user-attachments/assets/1e8ade73-7379-4ebf-b647-c06d51181d29)

Should take care of duplicates and empty names.

2025-02-04 09:56 UTC, basseche commented
When i duplicate limit sets names are the same and i can validate dialog !

2025-02-04 10:18 UTC, basseche commented
- Create a  limitSet name "LIMIT_SET"  is given, don't edit the name, add some limits inside and save
- Create a new limitSet name "LIMIT_SET" is given by default but you should edit it, edit the name => it edits the wrong limit sets name

2025-02-04 10:21 UTC, basseche commented
we can create duplicate name by clicking ouside or adding space at the end of the name

2025-02-04 11:50 UTC, Mathieu-Deharbe commented
> * Create a  limitSet name "LIMIT_SET"  is given, don't edit the name, add some limits inside and save
> * Create a new limitSet name "LIMIT_SET" is given by default but you should edit it, edit the name => it edits the wrong limit sets name

I added auto editing when duplicating a limit set and some extra security against duplicate names.

Let me know if you find a flaw in that security.

2025-02-04 13:27 UTC, basseche commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> +        let formattedCompleteLimitsGroups /*: OperationalLimitsGroup[]*/ = [];
const

2025-02-04 18:22 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> +        let formattedCompleteLimitsGroups /*: OperationalLimitsGroup[]*/ = [];
done.

2025-02-05 08:40 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/two-windings-transformer/modification/two-windings-transformer-modification-dialog.jsx
> +                ...getSelectedLimitsFormData({
why getValues(`${LIMITS}.${CURRENT_LIMITS_1}.${PERMANENT_LIMIT}`) ?

2025-02-05 08:58 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-side-pane.tsx
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
2025

2025-02-05 08:58 UTC, ghazwarhili commented on src/components/dialogs/limits/temporary-limits-table.tsx
> +        // note : an id prop is automatically added in each row
clean this comment

2025-02-05 08:58 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/two-windings-transformer/modification/two-windings-transformer-modification-dialog.jsx
> +                        twt.currentLimits2?.permanentLimit ??
permanentLimit1: twt.currentLimits1?.permanentLimit ??
permanentLimit2: twt.currentLimits2?.permanentLimit

2025-02-05 08:58 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/two-windings-transformer/creation/two-windings-transformer-creation-dialog.jsx
> +    ...getLimitsEmptyFormData(LIMITS, false),
remove this LIMITS
it is already id = LIMITS

2025-02-05 08:58 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +export const getLimitsEmptyFormData = (id = LIMITS, onlySelectedLimits = true) => {
```suggestion
export const getLimitsEmptyFormData = (onlySelectedLimits = true, id = LIMITS)
```

2025-02-05 08:58 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> +    ...getLimitsEmptyFormData(LIMITS, false),
```suggestion
    ...getLimitsEmptyFormData(false),
```

2025-02-05 08:58 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> +            ...getLimitsValidationSchema(LIMITS, false),
```suggestion
            ...getLimitsValidationSchema(false),
```

2025-02-05 09:06 UTC, ghazwarhili requested changes

2025-02-05 09:10 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane-utils.js
> +export const getLimitsEmptyFormData = (id = LIMITS, onlySelectedLimits = true) => {
OK done.

2025-02-05 09:15 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane.tsx
> +    currentNode?: CurrentTreeNode;
In line-creation `<LimitsPane />` is created without any prop. Looks like it is useful only for modifications.

2025-02-05 09:16 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-side-pane.tsx
> + * Copyright (c) 2024, RTE (http://www.rte-france.com)
Done.

2025-02-05 09:16 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/temporary-limits-table.tsx
> +        // note : an id prop is automatically added in each row
Done.

2025-02-05 09:16 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> +    ...getLimitsEmptyFormData(LIMITS, false),
Done.

2025-02-05 09:16 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> +            ...getLimitsValidationSchema(LIMITS, false),
Done.

2025-02-05 09:17 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/two-windings-transformer/creation/two-windings-transformer-creation-dialog.jsx
> +    ...getLimitsEmptyFormData(LIMITS, false),
done.

2025-02-05 09:19 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/two-windings-transformer/modification/two-windings-transformer-modification-dialog.jsx
> +                ...getSelectedLimitsFormData({
Looks like obsolete code that I should have removed when I resolved the conflicts with your correction about this. Removed.

2025-02-05 09:20 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/two-windings-transformer/modification/two-windings-transformer-modification-dialog.jsx
> +                        twt.currentLimits2?.permanentLimit ??
Do you mean : ?
```
permanentLimit1: twt.currentLimits1?.permanentLimit,
permanentLimit2: twt.currentLimits2?.permanentLimit,
```
This is what I commited.

2025-02-05 09:26 UTC, ghazwarhili commented on src/components/dialogs/limits/copy-limits.tsx
> +    id?: string;
```suggestion
    id: string;
```

2025-02-05 09:28 UTC, ghazwarhili commented on src/components/dialogs/limits/copy-limits.tsx
> +export function CopyLimits({ id = LIMITS, indexSelectedLimitSet1, indexSelectedLimitSet2 }: Readonly<CopyLimitsProps>) {
```suggestion
export function CopyLimits({ id, indexSelectedLimitSet1, indexSelectedLimitSet2 }: Readonly<CopyLimitsProps>) {
```

2025-02-05 09:28 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane.tsx
> +                        <CopyLimits
```suggestion
                        <CopyLimits
                            id={LIMITS}
                            indexSelectedLimitSet1={indexSelectedLimitSet1}
                            indexSelectedLimitSet2={indexSelectedLimitSet2}
                        />
```

2025-02-05 09:39 UTC, ghazwarhili commented on src/components/dialogs/limits/copy-limits.tsx
> +                <Button onClick={() => copyToRight()} sx={limitsStyles.copyLimitsButtons}>
```suggestion
                               <Button
                    onClick={copyToRight}
                    disabled={indexSelectedLimitSet2 === null}
                    sx={limitsStyles.copyLimitsButtons}
                >
```

2025-02-05 10:09 UTC, ghazwarhili commented on src/components/dialogs/limits/copy-limits.tsx
> +import React, { useCallback } from 'react';
remove the import React,
```suggestion
import { useCallback } from 'react';
```

2025-02-05 10:09 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-groups-contextual-menu.tsx
> +import React from 'react';
remove this import

2025-02-05 10:09 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane.tsx
> +    id?: string;
id: string;

2025-02-05 10:34 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-side-pane.tsx
>              const formattedTemporaryLimits = formatTemporaryLimits(temporaryLimits);
you have to check on the temporaryLimits lenght
```suggestion
                       if (!temporaryLimits?.length) {
                return undefined;
            }
```

2025-02-05 10:34 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-side-pane.tsx
>              if (shouldReturnPreviousValue(rowIndex, column, arrayFormName, formattedTemporaryLimits)) {
before this if we need to check if we should process the previous value 
```suggestion
            if (!shouldReturnPreviousValue(rowIndex, column, arrayFormName, formattedTemporaryLimits)) {
                return undefined;
            }
```

2025-02-05 10:34 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-side-pane.tsx
> +                    arrayFormName={`${limitsGroupFormName}.${TEMPORARY_LIMITS}`}
use const field for limitsGroupFormName

2025-02-05 11:46 UTC, ghazwarhili commented on src/components/dialogs/limits/operational-limits-groups-tabs.tsx
> +import React, { useCallback, useEffect, useState } from 'react';
```suggestion
import { useCallback, useEffect, useState } from 'react';
```

2025-02-05 11:49 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane.tsx
> +import React, { useState } from 'react';
the same here remove the import of React

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/copy-limits.tsx
> +export function CopyLimits({ id = LIMITS, indexSelectedLimitSet1, indexSelectedLimitSet2 }: Readonly<CopyLimitsProps>) {
I copied that "id" from previous component but never liked it. I renamed it as parentFormName and did as you suggested (made it mandatory).

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/copy-limits.tsx
> +                <Button onClick={() => copyToRight()} sx={limitsStyles.copyLimitsButtons}>
OK. Did the same for `copyToLeft`.

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-groups-contextual-menu.tsx
> +import React from 'react';
OK done.

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-groups-contextual-menu.tsx
> +    id?: string;
OK. Done the same that for the previous component.

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-groups-contextual-menu.tsx
> +    menuAnchorEl: any;
Typed as `PopoverProps['anchorEl']`

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane.tsx
> +    id?: string;
I kept this because this is how it was initially made (cf `<LimitsPane />` in `line-creation-dialog`). But I don't really like it. I changed it in my own props like you asked though.

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane.tsx
> +                        <CopyLimits
Done (but rename "id". I found it confusing.

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-side-pane.tsx
> +    permanentCurrentLimitPreviousValue: any;
Indeed I forgot this one sorry. Typed into `number | null`

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-side-pane.tsx
> +                    arrayFormName={`${limitsGroupFormName}.${TEMPORARY_LIMITS}`}
It can't be a const field : it changes according to the concerned side and selected limit set. This is why this is a prop.

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/operational-limits-groups-tabs.tsx
> +    id?: string;
Done. Changed like the similar components.

2025-02-05 11:55 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/operational-limits-groups-tabs.tsx
> +                {limitsGroups1.map((set: OperationalLimitsGroup, index: number) => (
Renamed into `opLg`. Is that Ok ?

2025-02-05 12:00 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> -                    equipmentId: line.id + '(1)',
why this changes ?
Put the code back as it was, no need to modify it so we stay consistent with the rest of the function code

2025-02-05 12:03 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> +        if (completeLimitsGroups) {
add nullability check for completeLimitsGroups (when line.currentLimits1 or line.currentLimits2 return null)

2025-02-05 12:11 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-side-pane.tsx
>              if (shouldReturnPreviousValue(rowIndex, column, arrayFormName, formattedTemporaryLimits)) {
Elegant. OK done.

2025-02-05 12:12 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-side-pane.tsx
>              const formattedTemporaryLimits = formatTemporaryLimits(temporaryLimits);
OK done.

2025-02-05 12:20 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/two-windings-transformer/modification/two-windings-transformer-modification-dialog.jsx
> +                )?.temporaryLimits,
I don't agree with the using of the addModificationTypeToTemporaryLimits function
 Try to simplify this code to avoid duplication and processing complexity
I suggest for example 
```suggestion
                 const { temporaryLimits1, temporaryLimits2 } = addModificationTypeToTemporaryLimits({
                limits: limits,
                currentLimitsData: lineToModify,
                editLimitsData: editData,
                currentNode,
            });
```

2025-02-05 12:26 UTC, ghazwarhili commented on src/services/study/network-modifications.ts
> +            [OPERATIONAL_LIMITS_GROUPS_2]: limitsGroups2,
Please try to write homogeneous code
```suggestion
            operationalLimitsGroups1: limitsGroups1,
            operationalLimitsGroups2: limitsGroups2,
```

2025-02-05 12:31 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane.tsx
> +    equipmentToModify?: any;
you have to create it (it is related to the object Line from map-server)

2025-02-05 13:27 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> +        if (completeLimitsGroups) {
Isn't `if (completeLimitsGroups) {` already a nullability check ?

2025-02-05 13:37 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> -                    equipmentId: line.id + '(1)',
I don't remember. Probably because the current format make "Find usages" a lot less effective and this caused me some problems. I also thought that this was the required format now. But ok done, I don't really care.

2025-02-05 13:37 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> -                    equipmentId: line.equipmentId,
And did the same.

2025-02-05 13:38 UTC, Mathieu-Deharbe commented on src/services/study/network-modifications.ts
> +            [OPERATIONAL_LIMITS_GROUPS_2]: limitsGroups2,
As you wish.

2025-02-05 14:07 UTC, etiennehomer commented on src/components/dialogs/limits/limits-pane.tsx
> +    equipmentToModify?: any;
Ideally we should type equipmentToModify yes. As much as possible, we try to not use "any" in the new code. 
But here, limits-pane.tsx is linked to many JS files or weakly typed files. And it's a big PR that we want to finish. So let's do the typing later

2025-02-05 14:20 UTC, Mathieu-Deharbe commented on src/components/dialogs/network-modifications/two-windings-transformer/modification/two-windings-transformer-modification-dialog.jsx
> +                )?.temporaryLimits,
I agree it could be improved but I didn't touch that code and line-modification isn't even the subject of this (already huge) PR.

2025-02-05 14:24 UTC, ghazwarhili commented on src/components/dialogs/limits/copy-limits.tsx
> +import React, { useCallback } from 'react';
not resolved yet

2025-02-05 14:26 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-groups-contextual-menu.tsx
> +                setValue(`${parentFormName}.${SELECTED_LIMITS_GROUP_2}`, '');
setValue(`${parentFormName}.${SELECTED_LIMITS_GROUP_2}`, null); ?

2025-02-05 14:28 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +                otherwise: () => yup.string().nullable(), // empty lines are ignored
you don't need this otherwise: () => yup.string().nullable(),

2025-02-05 14:30 UTC, ghazwarhili commented on src/components/dialogs/network-modifications/line/creation/line-creation-dialog.jsx
> +        if (completeLimitsGroups) {
my bad

2025-02-05 14:38 UTC, ghazwarhili commented on src/components/dialogs/limits/limits-pane-utils.js
> +const limitsValidationSchema = (id, onlySelectedLimits = true) => {
limitsValidationSchema is called only in  getLimitsValidationSchema = (onlySelectedLimits = true, id = LIMITS)

```suggestion
const limitsValidationSchema = (id, onlySelectedLimits) 
```

2025-02-05 15:32 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-groups-contextual-menu.tsx
> +                setValue(`${parentFormName}.${SELECTED_LIMITS_GROUP_2}`, '');
It doesn't work.

2025-02-05 15:35 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane-utils.js
> +const limitsValidationSchema = (id, onlySelectedLimits = true) => {
Indeed. Changed.

2025-02-05 15:35 UTC, Mathieu-Deharbe commented on src/components/dialogs/limits/limits-pane-utils.js
> +                otherwise: () => yup.string().nullable(), // empty lines are ignored
True. Removed.

2025-02-05 15:36 UTC, basseche commented
we can create limits with name but no values ! 

![Capture d’écran du 2025-02-05 16-36-14](https://github.com/user-attachments/assets/87d271f1-bfbd-45b6-8ca1-1bd62b63f07d)

2025-02-05 15:45 UTC, Mathieu-Deharbe commented
> we can create limits with name but no values !
> 
> ![Capture d’écran du 2025-02-05 16-36-14](https://private-user-images.githubusercontent.com/178886530/410061730-87d271f1-bfbd-45b6-8ca1-1bd62b63f07d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg3NzA1MjUsIm5iZiI6MTczODc3MDIyNSwicGF0aCI6Ii8xNzg4ODY1MzAvNDEwMDYxNzMwLTg3ZDI3MWYxLWJmYmQtNDViNi04Y2ExLTFiZDYyYjYzZjA3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwNVQxNTQzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmM2ZjgyMDM2MWVmNWIxNGQyMGEzZmQxNTA2M2I1MjAyNzg1ZmUzZTQ3OTkxY2ZmN2U2ZjRkNzhmMTk0OTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8SYjSVx7bWqEzIwuZ6JmT0Ns9joIWoGmRNTewZ6XzYk)

I agree that this is missing but nothing new. This control doesn't exist neither in prod nor in dev-opf.

2025-02-05 16:25 UTC, basseche commented
> > we can create limits with name but no values !
> > ![Capture d’écran du 2025-02-05 16-36-14](https://private-user-images.githubusercontent.com/178886530/410061730-87d271f1-bfbd-45b6-8ca1-1bd62b63f07d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg3NzA1MjUsIm5iZiI6MTczODc3MDIyNSwicGF0aCI6Ii8xNzg4ODY1MzAvNDEwMDYxNzMwLTg3ZDI3MWYxLWJmYmQtNDViNi04Y2ExLTFiZDYyYjYzZjA3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIwNVQxNTQzNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YmM2ZjgyMDM2MWVmNWIxNGQyMGEzZmQxNTA2M2I1MjAyNzg1ZmUzZTQ3OTkxY2ZmN2U2ZjRkNzhmMTk0OTA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8SYjSVx7bWqEzIwuZ6JmT0Ns9joIWoGmRNTewZ6XzYk)
> 
> I agree that this is missing but nothing new. This control doesn't exist neither in prod nor in dev-opf.

The behavior is alredy present on Dev OPF so nothing new  i close this thread

2025-02-06 09:49 UTC, basseche approved these changes

2025-02-06 16:33 UTC, ghazwarhili approved these changes
Even though the code still needs a lot of work and several things need to be properly redone, since it's a big task and has been dragging on for a while, I approve merging it now, and we will improve it in other PRs

2025-02-10 14:09 UTC, merged