add substation creation to voltagelevel creation form
gridsuite/gridstudy-app pull request #2439
Opened 2024-12-06 16:14 UTC by ghazwarhili

2024-12-17 13:28 UTC, basseche commented
as discussed with PO you have to make some changes to :
- add a separator line or better to isolate the substation creation
- correct editing of substation creation (see all fields).

2024-12-17 13:30 UTC, basseche requested changes
as discussed with PO you have to make some changes to :
- add a separator line or better to isolate the substation creation
- correct editing of substation creation (see all fields).
- add "add property" button to add properties to substation

2025-01-16 11:15 UTC, basseche requested changes

2025-01-16 11:15 UTC, basseche commented on src/components/dialogs/network-modifications/voltage-level/creation/voltage-level-creation-form.jsx
> +        const currentSubstationId = getValues(`${SUBSTATION_ID}`);
i don't understand why you use `${SUBSTATION_ID}` here it will be the same and simpler to use SUBSTATION_ID directly

2025-01-16 11:15 UTC, basseche commented on src/components/dialogs/network-modifications/voltage-level/creation/voltage-level-creation-form.jsx
> +            setValue(`${SUBSTATION_ID}`, null);
same here

2025-01-16 14:26 UTC, basseche commented
there is an issue on substation deletion,  : substation is neither deleted or removed from voltageLevelCreation 

![bug](https://github.com/user-attachments/assets/d5e39aaa-b35a-461f-896e-91810ad04159)

2025-01-17 06:50 UTC, ghazwarhili commented
@basseche 
-> Create a voltageLevel with a create substation for s1.
-> Edit the creation hypothesis for the voltageLevel to change the substation:
       -> Click on the remove button, then go back to the list of available substations.

=> This does not mean that you have deleted the substation you just created s1 (you must follow a separate hypothesis for substation deletion).

=> The role of the remove button is visual, not functional.

2025-01-17 08:20 UTC, basseche commented
> @basseche
> 
> -> Create a voltageLevel along with a create substation for s1. -> To edit the substation associated with the voltageLevel: -> Click the remove button, then return to the list of available substations.
> 
> Note: This does not mean you have deleted the substation you just created (s1). Substation deletion requires following a separate procedure.
> 
> Important: The role of the remove button is purely visual and not functional (refer to the US description).
> 
> @etiennehomer Can you confirm this?

Sorry but i don't agree. I should be able to cancel the substation creation if i want. And suppose even that it doesn't cancel it, i should be able at least to cancel the choice of the susbstation in my VoltageLevel creation.

2025-01-17 12:02 UTC, basseche commented on src/components/dialogs/network-modifications/voltage-level/creation/voltage-level-creation-form.jsx
> +                return (
Look at sonar warning : "Move this component definition out of the parent component and pass data as props."

2025-01-24 14:55 UTC, EtienneLt approved these changes
test Ok

2025-01-27 18:19 UTC, merged