new IHM : root network
gridsuite/gridstudy-app pull request #2457
Opened 2024-12-17 13:12 UTC by souissimai

2025-01-20 10:03 UTC, klesaulnier requested changes
regroup root-network files into a specific folder ? 
here you can find them in 
- components
- components/graph/menus
- components/dialogs

2025-01-20 10:04 UTC, klesaulnier commented on src/components/diagrams/diagram-pane.tsx
> +    // This effect will trigger the diagrams' forced update
fixed

2025-01-20 10:05 UTC, klesaulnier commented on src/components/diagrams/diagram-pane.tsx
> +
fixed

2025-01-20 10:05 UTC, klesaulnier commented on src/components/diagrams/diagram-pane.tsx
> +
fixed

2025-01-20 10:05 UTC, klesaulnier commented on src/components/dialogs/network-modifications/two-windings-transformer/creation/two-windings-transformer-creation-dialog.jsx
> +
fixed

2025-01-20 10:06 UTC, klesaulnier commented on src/components/dialogs/network-modifications/two-windings-transformer/modification/two-windings-transformer-modification-dialog.jsx
> + * @param currentRootNetworkUuid The current root network uuid we are currently working on
fixed

2025-01-20 10:06 UTC, klesaulnier commented on src/components/network-modification-tree-pane.jsx
> +        //   backgroundColor: 'yellow',
fixed

2025-01-20 10:07 UTC, klesaulnier commented on src/components/network-modification-tree.jsx
> +                {/* root Network Panel */}
fixed

2025-01-20 10:07 UTC, klesaulnier commented on src/components/network/network-map-tab.tsx
> +
fixed

2025-01-20 10:08 UTC, klesaulnier commented on src/components/network/network-map-tab.tsx
> +        geoDataRef.current = null;
fixed

2025-01-20 10:11 UTC, klesaulnier commented on src/components/network/network-map-tab.tsx
> +        }
fixed

2025-01-20 10:11 UTC, klesaulnier commented on src/components/network/network-map-tab.tsx
> +            }
fixed

2025-01-20 10:13 UTC, klesaulnier commented on src/services/network-conversion.ts
> +export function getCaseImportParameters(caseUuid: UUID | undefined): Promise<GetCaseImportParametersReturn> {
fixed

2025-01-20 10:13 UTC, klesaulnier commented on src/services/root-network.ts
> +export const PREFIX_STUDY_QUERIES = import.meta.env.VITE_API_GATEWAY + '/study';
fixed

2025-01-20 10:14 UTC, klesaulnier commented on src/services/root-network.ts
> +    console.info('Fetching root network for studyUuid : ', studyUuid);
fixed

2025-01-20 10:15 UTC, klesaulnier commented on src/services/root-network.ts
> +    importParameters: Record<string, any>
fixed

2025-01-20 10:15 UTC, klesaulnier commented on src/services/root-network.ts
> +    }
fixed

2025-01-20 10:16 UTC, klesaulnier commented on src/services/root-network.ts
> +export function rootNetworkNameExists(studyUuid: UUID, name: string): Promise<boolean> {
fixed

2025-01-20 10:17 UTC, klesaulnier commented on src/translations/en.json
> +    "rootNetworkNotFound": "No root network was not found for the study with ID \"{studyUuid}\"",
fixed

2025-01-20 10:21 UTC, klesaulnier commented on src/translations/en.json
> +    "errCreateRootNetworksMsg": "Root Networks creation error",
fixed

2025-01-20 10:21 UTC, klesaulnier commented on src/translations/en.json
> +    "rootNetworknameValidityCheckErrorMsg": "Error while checking name validity"
fixed

2025-01-20 10:22 UTC, klesaulnier commented on src/translations/fr.json
> +    "rootNetworknameValidityCheckErrorMsg": "Erreur à la vérification du nom de réseau racine"
fixed

2025-01-20 10:23 UTC, klesaulnier commented on src/translations/fr.json
> +    "RootNetworkNotFound": "Aucun réseau racine n'a été trouvé pour l'étude avec l'ID \"{studyUuid}\"",
fixed

2025-01-20 10:39 UTC, klesaulnier commented on src/components/dialogs/root-network-creation-dialog.tsx
> +    const [selectedCase, setSelectedCase] = useState<TreeViewFinderNodeProps | null>(null);
removed

2025-01-20 11:25 UTC, klesaulnier commented on src/translations/en.json
> +    "rootNetworksCount":"{hide, select, false {{count, plural, =0 {no root} =1 {{count} Root} other {{count} Roots}}} other {...}}",
fixed

2025-01-20 11:27 UTC, klesaulnier commented on src/components/graph/menus/root-network-node-editor.tsx
> +                });
partially fixed, I think we should handle "creation / deletion in progress" with notifications instead

2025-01-20 11:27 UTC, klesaulnier commented on src/components/graph/menus/root-network-node-editor.tsx
> +    }, [notificationIdList, currentNode?.id]);
removed for now, I don't know why it was here

2025-01-20 11:28 UTC, klesaulnier commented on src/components/graph/menus/root-network-node-editor.tsx
> +        }
removed

2025-01-20 11:28 UTC, klesaulnier commented on src/components/graph/menus/root-network-node-editor.tsx
> +                }}
removed

2025-01-20 11:28 UTC, klesaulnier commented on src/components/graph/menus/root-network-node-editor.tsx
> +    };
fixed

2025-01-20 11:29 UTC, klesaulnier commented on src/components/graph/menus/root-network-node-editor.tsx
> +                dialogProps={undefined}
fixed

2025-01-20 13:14 UTC, souissimai commented on src/translations/en.json
> +    "ChooseSituation": "Select a case",
done

2025-01-22 16:33 UTC, souissimai commented on src/redux/reducer.ts
> +        state.reloadMap = true;
it should be deleted !

2025-01-23 09:04 UTC, souissimai commented on src/components/diagrams/diagram-pane.tsx
> +            }
to update diagram only for concerned root network

2025-01-23 09:11 UTC, souissimai commented on src/components/results/shortcircuit/shortcircuit-analysis-result.tsx
> +        }
we can not fetchShortCircuitAnalysisPagedResults if currentrootnetwork is null

2025-01-23 09:15 UTC, souissimai commented on src/components/study-container.jsx
> +            }
we display errot notification only for concerned rootnetwork

2025-01-23 09:16 UTC, souissimai commented on src/components/study-container.jsx
> +            }
to check if alert notif is related to current root network

2025-01-23 09:19 UTC, souissimai commented on src/components/study-container.jsx
> +                    }
done

2025-01-23 09:21 UTC, souissimai commented on src/hooks/use-get-study-impacts.ts
> +            }
StUDY notification depends on root network

2025-01-23 09:52 UTC, klesaulnier commented on src/components/diagrams/diagram-pane.tsx
> +            }
ok, fixed by 
            if (
                studyUpdatedForce.eventData.headers['rootNetwork'] !== currentRootNetworkRef.current
            ) {
                return;
            }

2025-01-23 09:58 UTC, klesaulnier commented on src/components/computing-status/use-computing-status.ts
> +    }
ok, renamed rootNetworkUuid by rootNetworkUuidFromNotification

2025-01-23 10:36 UTC, souissimai commented on src/components/study-container.jsx
> +    }
already discussed

2025-01-23 10:42 UTC, souissimai commented on src/components/study-container.jsx
> +                fetchRootNetworks(studyUuidRequest)
when fetching study and checking that it exists we affect first root network what do you think?

2025-01-23 10:52 UTC, souissimai commented on src/components/graph/menus/root-network-node-editor.tsx
> +                });
changed

2025-01-23 14:38 UTC, FranckLecuyer approved these changes

2025-01-23 14:45 UTC, FranckLecuyer approved these changes
Code review: only commit https://github.com/gridsuite/gridstudy-app/pull/2457/commits/8a1e631a1b252580075040e6feb93815473486c4

2025-01-24 08:15 UTC, klesaulnier commented on src/components/graph/menus/root-network-node-editor.tsx
> +            if (selectedRootNetworksUuid.length === 1) {
fixed

2025-01-29 14:41 UTC, klesaulnier approved these changes

2025-01-29 14:41 UTC, merged