[WIP] feat: reference nodes in custom columns spreadsheet
gridsuite/gridstudy-app pull request #2469
Opened 2024-12-24 12:12 UTC by AbdelHedhili

2025-01-13 09:37 UTC, AbdelHedhili commented
Known possible improvement: 
for now, we redo the fetch to get the information of other nodes whenever we get to a tab that uses a custom column with a node because we don't know if the data is still up-to-date. We could use notification to only redo fetches when necessary.

2025-01-15 10:01 UTC, Meklo commented on src/components/spreadsheet/table-wrapper.tsx
> +                        let equipmentWithAddedInfo: any = { ...matchingEquipment };
I reckon it could be typed as follow :
`export interface RecursiveIdentifiable extends Identifiable {
    [alias: string]: Identifiable | unknown;
}
`

2025-01-15 10:09 UTC, Meklo commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +            return tablesDefinitions.filter(
Same comment as for `toSpreadsheetEquipmentType` in `table-wrapper`

2025-01-15 10:28 UTC, Meklo commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> -                    setIsFetching(false);
Why this removal ?

2025-01-16 11:17 UTC, AbdelHedhili commented on src/components/spreadsheet/custom-columns/use-custom-column.ts
> +                    return math.limitedEvaluate(colWithFormula.formula ?? '', scope);
its a remaining of a previous solution that i removed but forgot this

2025-01-16 11:21 UTC, AbdelHedhili commented on src/components/spreadsheet/table-wrapper.tsx
> +            return tablesDefinitions.filter(
The thing is it's never supposed to be null since every equipment has a type but yeah if for whatever reason this happens it's better to not crash. I guess in this case we could just do nothing (not updating the rowdata)

2025-01-17 10:08 UTC, TheMaskedTurtle requested changes

2025-01-17 10:08 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                            aliasesAlreadyFound.push(alias);
Why do you introduce all this complexity ? Why not just fetching all the data related to all the nodes defined in the customColumnsNodesAliases ?

2025-01-17 10:08 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                    dispatch(addAdditionalEquipmentsByNodesForCustomColumns(additionalEquipmentsByNodes));
Why do you create additional data in the redux for this ? Why not directly in the spreadsheetNetwork ?

2025-01-17 10:08 UTC, TheMaskedTurtle commented on src/components/spreadsheet/table-wrapper.tsx
> +        const equipmentType = toSpreadsheetEquipmentType(tablesNames[tabIndex]);
This additionnal treatment and use of new selectors won't be necessary if you use spreadsheetNetwork directly

2025-01-17 11:00 UTC, AbdelHedhili commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                            aliasesAlreadyFound.push(alias);
but that's precisely what i'm trying to do here or i'm not understanding what you're saying ? I can't just fetch the data for every customcolumn without keeping trace of what i already fetch or i would be doing 50 time the same fetch

2025-01-17 11:08 UTC, AbdelHedhili commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                            aliasesAlreadyFound.push(alias);
Oh ok i got it wrong, I understand what you mean, but it's not great to do that, we would be fetching a lot of data we don't actually need if we fetch all the data of the nodes that are found in aliases

2025-01-17 11:20 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                            aliasesAlreadyFound.push(alias);
And I'm not a big fan of parsing formulas like that I think for now we should avoid this.

2025-01-17 11:22 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                            aliasesAlreadyFound.push(alias);
And for me you only have one fetch to do when you add a new node in the node aliases list, this is absolutely not related to custom columns or even "traditional" columns. It's just that you want to load additionnal data

2025-01-17 11:34 UTC, AbdelHedhili commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                    dispatch(addAdditionalEquipmentsByNodesForCustomColumns(additionalEquipmentsByNodes));
I thought it's better to have the other nodes info in a seperate state because its probable that it won't behave exactly as the current data info

2025-01-17 11:46 UTC, AbdelHedhili commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +    );
Yep, I missed it. Thanks

2025-01-17 12:10 UTC, AbdelHedhili commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                            aliasesAlreadyFound.push(alias);
I don't know... So the user add 2 customs columns one "alias1.maxP" and "alias2.maxP" only for the generators and we would end up with 3 whole network loaded in the front. That seems so unreasonable, that's why i did it this way.

2025-01-17 12:13 UTC, AbdelHedhili commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                            aliasesAlreadyFound.push(alias);
> And for me you only have one fetch to do when you add a new node in the node aliases list, this is absolutely not related to custom columns or even "traditional" columns. It's just that you want to load additionnal data

But it is related, this node alias option is only here to define the aliases used in... the custom columns. It was not defined as a load the network with this id. It's a this alias = this node in the custom column

2025-01-17 12:45 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                            aliasesAlreadyFound.push(alias);
For now, but in a really near future all columns will be "custom" columns, then it won't make any difference. And do we agree that the fetcher is loading all data for one type of equipment anyway ? It doesn't load just the data you need in the column ? So what you did just postpone the moment we're fetching the related equipments data of the new node (when you use it in a column) but it does not make a great difference if you fetch them node/alias declaration directly.

2025-01-17 12:47 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                    dispatch(addAdditionalEquipmentsByNodesForCustomColumns(additionalEquipmentsByNodes));
I think that's the whole point, it should behave exactly the same. So that, we just load more data initially and then nothing else changes in the code.

2025-01-17 12:55 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                            aliasesAlreadyFound.push(alias);
But yes we have to think about this conception considering what will be the final usage of the spreadsheet. All columns will be customizable, and we will be able to load several nodes of the network for one given equipment type. So we have to think about it like 2 distinct systems, the node/alias system enables to fill more available data in our spreadhseet, and the custom column system that enables the users to combine nodes data as they want.

2025-01-21 11:28 UTC, TheMaskedTurtle requested changes

2025-01-21 11:28 UTC, TheMaskedTurtle commented on src/components/spreadsheet/custom-columns/custom-columns-nodes-dialog.tsx
> +    const formMethods = useForm({
```suggestion
    const formMethods = useForm<CustomColumnNodesForm>({
```

2025-01-21 11:28 UTC, TheMaskedTurtle commented on src/components/spreadsheet/custom-columns/custom-columns-nodes-dialog.tsx
> +    };
```suggestion
const onValidate = (data: CustomColumnNodesForm) => {
        onClose();
        dispatch(updateCustomColumnsNodesAliases(data.nodesAliases));
    };
```

2025-01-21 11:28 UTC, TheMaskedTurtle commented on src/components/spreadsheet/custom-columns/custom-columns-nodes-dialog.tsx
> +    };
```suggestion
const onClose = () => {
        open.setFalse();
        reset(initialCustomColumnNodesForm);
    };
```

2025-01-21 11:28 UTC, TheMaskedTurtle commented on src/components/spreadsheet/table-wrapper.tsx
> +    [alias: string]: Identifiable | unknown;
```suggestion
    [alias: string]: Identifiable | string;
```

2025-01-21 11:28 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +            let fetchers: Promise<any>[] = [];
```suggestion
            let fetchers: Promise<unknown>[] = [];
```

2025-01-21 11:30 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                    dispatch(addAdditionalEquipmentsByNodesForCustomColumns(additionalEquipmentsByNodes));
ok we'll wee that in another ticket

2025-01-21 11:30 UTC, TheMaskedTurtle commented on src/components/spreadsheet/table-wrapper.tsx
> +        const equipmentType = toSpreadsheetEquipmentType(tablesNames[tabIndex]);
Yes, we'll see that in another ticket

2025-01-21 13:05 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                    )?.name;
directly iterate through customColumnsNodesAliases to get the names ?

2025-01-21 13:05 UTC, TheMaskedTurtle commented on src/components/spreadsheet/use-spreadsheet-equipments.ts
> +                    )?.name;
Can't we store the node UUIDs directly and the names would be only used for displaying purposes in the autocomplete ? But behind the scene we only UUIDs ? I think it would be a bit more robust

2025-01-21 16:49 UTC, TheMaskedTurtle approved these changes

2025-01-22 09:02 UTC, Meklo approved these changes

2025-01-22 09:03 UTC, merged