[WIP] Allow the slider to move with the mouse
gridsuite/gridstudy-app pull request #311
Opened 2021-03-05 15:21 UTC by niconoir

2021-03-10 12:49 UTC, AbdelHedhili approved these changes

2021-03-11 07:55 UTC, geofjamg requested changes
When we open a study with overload table already checked, the slider is disable we have to uncheck and recheck.

![image](https://user-images.githubusercontent.com/632675/110753940-7d375800-8247-11eb-90b9-21afed243515.png)

2021-03-11 08:23 UTC, geofjamg commented
> When we open a study with overload table already checked, the slider is disable we have to uncheck and recheck.
> 
> ![image](https://user-images.githubusercontent.com/632675/110753940-7d375800-8247-11eb-90b9-21afed243515.png)

Seem to be already present in master

2021-03-11 08:25 UTC, geofjamg approved these changes

2021-03-11 08:25 UTC, merged