Add root tree node uuid in calls to study server
gridsuite/gridstudy-app pull request #408
Opened 2021-11-23 14:27 UTC by FranckLecuyer

2021-11-26 13:28 UTC, niconoir requested changes
Some comments related to redux usage

2021-11-26 13:28 UTC, niconoir commented on src/redux/actions.js
> +        selectTreeNode: selectTreeNode,
Rename as selectedTreeNode ?

2021-11-26 13:28 UTC, niconoir commented on src/components/line-menu.js
> +        const selectedNodeUuid = useSelector((state) => state.selectTreeNode);
Maybe pass selectedNodeUuid as a prop if possible ?

2021-11-26 14:42 UTC, FranckLecuyer commented on src/redux/reducer.js
> +    selectTreeNode: null,
Done

2021-11-26 14:42 UTC, FranckLecuyer commented on src/components/dialogs/connectivity-edition.js
> +    const selectedNodeUuid = useSelector((state) => state.selectTreeNode);
Done

2021-11-26 14:42 UTC, FranckLecuyer commented on src/components/contingency-list-selector.js
> +    const selectedNodeUuid = useSelector((state) => state.selectTreeNode);
Done

2021-11-26 14:42 UTC, FranckLecuyer commented on src/components/dialogs/equipment-deletion-dialog.js
> +    const selectedNodeUuid = useSelector((state) => state.selectTreeNode);
Done

2021-11-26 14:42 UTC, FranckLecuyer commented on src/components/dialogs/generator-creation-dialog.js
> +    const selectedNodeUuid = useSelector((state) => state.selectTreeNode);
Done

2021-11-26 14:43 UTC, FranckLecuyer commented on src/components/dialogs/line-creation-dialog.js
> +    const selectedNodeUuid = useSelector((state) => state.selectTreeNode);
Done

2021-11-26 14:43 UTC, FranckLecuyer commented on src/components/dialogs/load-creation-dialog.js
> +    const selectedNodeUuid = useSelector((state) => state.selectTreeNode);
Done

2021-11-26 14:43 UTC, FranckLecuyer commented on src/components/dialogs/two-windings-transformer-creation-dialog.js
> +    const selectedNodeUuid = useSelector((state) => state.selectTreeNode);
Done

2021-11-26 14:43 UTC, FranckLecuyer commented on src/redux/actions.js
> +        selectTreeNode: selectTreeNode,
Done

2021-11-26 14:43 UTC, FranckLecuyer commented on src/components/line-menu.js
> +        const selectedNodeUuid = useSelector((state) => state.selectTreeNode);
Done

2021-11-30 14:16 UTC, niconoir approved these changes

2021-12-01 17:13 UTC, SlimaneAmar commented on src/redux/reducer.js
> +    selectedTreeNode: null,
Use an object study {uuid, nodeuuid } ?

2021-12-02 10:57 UTC, SlimaneAmar approved these changes

2021-12-02 13:13 UTC, merged