WIP Us 755 create linear shunt compensator
gridsuite/gridstudy-app pull request #434
Opened 2022-01-25 09:46 UTC by JacquesBorsenberger

2022-01-25 12:12 UTC, laurgarn commented on src/components/util/validation-functions.js
> +    function toNumber(val) {
Yeah :-)

2022-01-26 13:53 UTC, laurgarn approved these changes

2022-01-26 13:53 UTC, laurgarn commented on src/translations/network-modifications-en.json
> +
Empty line that may disalign en and fr translations, no ?

2022-01-27 13:25 UTC, niconoir requested changes
Some logs to be removed

2022-01-27 13:28 UTC, JacquesBorsenberger commented on src/components/util/validation-functions.js
> +            console.info('jbo max', maxValue);
done

2022-01-27 13:29 UTC, JacquesBorsenberger commented on src/components/util/validation-functions.js
> +                console.info('jbo not nan ');
done

2022-01-27 13:29 UTC, JacquesBorsenberger commented on src/components/dialogs/input-hooks.js
> +    const [errorBusBarSection, setBusBarSection] = useState();
done

2022-01-27 13:46 UTC, niconoir approved these changes

2022-01-28 14:10 UTC, merged