Us 844 reorder network modification via drag and drop
gridsuite/gridstudy-app pull request #502
Opened 2022-04-08 11:38 UTC by JacquesBorsenberger

2022-04-11 15:14 UTC, archendel commented
maybe it could be nice to think about a lock to the drag and drop mecanism while the backend is processing the modification to avoid several simultaneous requests waiting for a response, which might cause some unexpected behaviours

2022-04-12 13:15 UTC, archendel requested changes
Use URLSearchParams

2022-04-12 13:23 UTC, etiennehomer requested changes

2022-04-12 13:24 UTC, etiennehomer commented on src/utils/rest-api.js
> +    idBefore
itemUuid and beforeUuid  ?

2022-04-12 14:03 UTC, JacquesBorsenberger commented on src/utils/rest-api.js
> +        (idBefore !== undefined ? '?before=' + idBefore : '');
done

2022-04-12 15:23 UTC, etiennehomer requested changes

2022-04-12 15:23 UTC, etiennehomer commented on src/components/graph/menus/network-modification-node-editor.js
> +            if (destination === null) return;
To avoid useless requests :
if (destination === null || source.index === destination.index) return;

2022-04-13 09:43 UTC, archendel approved these changes

2022-04-14 07:59 UTC, merged