Load modification modification dialog
gridsuite/gridstudy-app pull request #508
Opened 2022-04-11 14:45 UTC by niconoir

A new network modification dialog to create a load modification modification.

2022-04-15 15:16 UTC, FranckLecuyer requested changes

2022-04-15 15:16 UTC, FranckLecuyer commented on src/components/dialogs/load-modification-dialog.js
> +const LOAD_TYPES = [
duplicated from load-creation-dialog

2022-04-19 09:20 UTC, niconoir commented on src/components/dialogs/load-modification-dialog.js
> + * @param editData the data to edit
Parameter description added

2022-04-19 09:20 UTC, niconoir commented on src/components/dialogs/load-modification-dialog.js
> +    workingNodeUuid: PropTypes.string,
equipmentOptions prop type added

2022-04-19 09:22 UTC, FranckLecuyer requested changes

2022-04-19 09:25 UTC, niconoir commented on src/utils/rest-api.js
> +    isUpdate = false,
Removed

2022-04-19 09:40 UTC, FranckLecuyer approved these changes

2022-04-20 09:23 UTC, jonenst approved these changes

2022-04-20 09:28 UTC, merged