add generator modification
gridsuite/gridstudy-app pull request #537
Opened 2022-05-12 12:15 UTC by JacquesBorsenberger

Signed-off-by: jacques borsenberger <jacques.borsenberger@rte-france.com>

2022-05-18 13:52 UTC, niconoir requested changes

2022-05-18 13:52 UTC, niconoir commented on src/components/dialogs/generator-modification-dialog.js
> +                            {/* TODO message */}
Can be removed ?

2022-05-19 07:31 UTC, niconoir approved these changes

2022-05-20 14:06 UTC, JacquesBorsenberger commented on src/components/dialogs/generator-modification-dialog.js
> +                            {/* TODO message */}
ddone

2022-05-20 14:06 UTC, JacquesBorsenberger commented on src/components/dialogs/generator-modification-dialog.js
> +        previousValue: generatorInfos?.targetP,
done

2022-05-20 14:06 UTC, JacquesBorsenberger commented on src/components/dialogs/generator-modification-dialog.js
> +        previousValue: generatorInfos?.p,
done

2022-05-23 07:07 UTC, merged