add current node name in topbar
gridsuite/gridstudy-app pull request #542
Opened 2022-05-16 13:52 UTC by bendaamerahm

- putting the name of current node between the title and tabs  "Map"
- truncate node name if longer than 20 character  by adding three dots 
- adding tooltip to the node name that show the entire name text

2022-05-16 14:47 UTC, sBouzols requested changes

2022-05-16 14:47 UTC, sBouzols commented on src/components/app-top-bar.js
> +                    .then((res) => {
not sure it's the role of the TopBar Component to fetch NetworkModificationTree...

2022-05-16 14:47 UTC, sBouzols commented on src/redux/reducer.js
> +    CURRENT_NODE,
Why not using the already existing WORKING_TREE_NODE ?

2022-05-16 14:55 UTC, bendaamerahm commented on src/components/app-top-bar.js
> +        color: `${LIGHT_THEME}`,
ill change it  with theme.palette.primary.main

2022-05-20 15:20 UTC, sBouzols requested changes

2022-05-20 15:20 UTC, sBouzols commented on src/components/network-modification-tree-pane.js
> +
Remove this fetch and use `NetworkModificationTreeModel` in the redux which is the TreeModel

2022-05-20 15:20 UTC, sBouzols commented on src/components/network-modification-tree-pane.js
> +                    const res = values.find(({ id }) => {
the find is duplicated

2022-05-20 15:20 UTC, sBouzols commented on src/components/network-modification-tree-pane.js
> +                    studyUpdatedForce.eventData.headers['nodes'][0] ===
// TODO manage multiple delete notification later

2022-05-20 15:20 UTC, sBouzols commented on src/components/network-modification-tree.js
> +            dispatch(
restore order

2022-05-25 13:17 UTC, sBouzols requested changes

2022-05-25 13:17 UTC, sBouzols commented on src/components/network-modification-tree.js
> +            const rootNode = treeModel?.treeElements.find(
Use `getFirstNodeOfType` here

2022-05-30 13:57 UTC, sBouzols approved these changes
Code Review ok
Tests done :
* light/dark theme
* tree node navigation
* tabs navigation
* Node renaming synchro
* Node deletion synchro
OK

2022-06-01 08:36 UTC, merged