[WIP] Line attachment modification creation
gridsuite/gridstudy-app pull request #549
Opened 2022-05-19 15:37 UTC by niconoir

2022-05-31 11:23 UTC, FranckLecuyer requested changes

2022-05-31 11:23 UTC, FranckLecuyer commented on src/components/dialogs/line-split-or-attach-utils.js
> +// functiuons for useComplementaryPercentage
Typo

2022-06-03 13:41 UTC, archendel requested changes
Some visual and functional bugs to fix

2022-06-07 13:55 UTC, niconoir commented on src/components/dialogs/line-split-or-attach-utils.js
> +// functiuons for useComplementaryPercentage
Corrected and added copyright header

2022-06-07 14:07 UTC, niconoir commented on src/components/dialogs/dialogUtils.js
> +            delete data[key];
The point here is to remove object _data_ properties which have a null value, not to remove a null element from an array.

2022-06-07 14:24 UTC, niconoir commented on src/components/dialogs/line-split-or-attach-utils.js
> +                        variant="standard"
`variant="standard"` set to right field (makes it fully visible)

2022-06-07 15:54 UTC, niconoir commented on src/components/dialogs/line-attach-to-voltage-level-dialog.js
> +    const [voltageLevelOrId, voltageLevelIdField, setVoltageLevelOrId] =
Corrected an error in network-modification-server (error when retrieving modification attributes from database)

2022-06-07 15:55 UTC, niconoir commented on src/components/dialogs/line-attach-to-voltage-level-dialog.js
> +    const handleSave = () => {
Check added to ensure line creation attributes have been filled out.

2022-06-07 15:56 UTC, niconoir commented on src/components/dialogs/line-attach-to-voltage-level-dialog.js
> +                        {gridItem(
Added a non modifiable text field containing the id of the attached line (which should have been filled out in the line creation form)

2022-06-08 07:10 UTC, niconoir commented on src/components/dialogs/line-attach-to-voltage-level-dialog.js
> +                        {gridItem(
Ok with that. Modification done.

2022-06-08 07:10 UTC, niconoir commented on src/components/dialogs/line-attach-to-voltage-level-dialog.js
> +                            <Button
Ok with that. Modification done.

2022-06-08 07:15 UTC, niconoir commented on src/components/dialogs/line-attach-to-voltage-level-dialog.js
> +                    bobbss = [...bobbss, ...voltageLevelOrId.busbarSections];
I did not succeed to reproduce the bug following your instructions. Maybe was already corrected by backend service modifications.

2022-06-08 09:32 UTC, FranckLecuyer approved these changes

2022-06-08 12:49 UTC, archendel commented on src/components/dialogs/line-attach-to-voltage-level-dialog.js
> +                    bobbss = [...bobbss, ...voltageLevelOrId.busbarSections];
The error does not happened anymore at this state, but does happen when you try to rerender the node :

Add those two step to the above procedure to reproduce the error :
- create the hypothesis by selecting the previously created voltage level
- rerender the node
  => error

2022-06-08 15:12 UTC, archendel commented on src/components/dialogs/line-attach-to-voltage-level-dialog.js
> +                    bobbss = [...bobbss, ...voltageLevelOrId.busbarSections];
OK after updating backend to the latest version

2022-06-08 15:13 UTC, archendel approved these changes
Tested : OK

2022-06-10 13:06 UTC, merged