Add values to transformer spreadsheet
gridsuite/gridstudy-app pull request #554
Opened 2022-05-23 17:08 UTC by bendaamerahm

- Add values under  Two Windings Transformers spreadsheet
- Add values under  Three Windings Transformers spreadsheet
- create new param to columns definition (boolean: true | false)
- handle the case when data is boolean (true/false) by rendring a new Element (checkbox)

2022-05-24 14:40 UTC, sBouzols commented on src/translations/fr.json
> +    "RegulatingRatio" : "RÉGLEUR  EN RÉGLAGE",
remove one whitespace here

2022-05-24 14:40 UTC, sBouzols commented on src/components/network/network-table.js
> +                    // check if param boolean is true then render a boolean cell(checkbox)
seems obvious comment but ok

2022-05-24 14:40 UTC, sBouzols commented on src/components/network/network-table.js
> +                                //onClick={handleCheckboxClick} #TODO handle change event later
Remove dead code

2022-05-24 14:43 UTC, sBouzols commented on src/components/network/config-tables.js
> +                boolean: true, // new param to indicate that this cell data is boolean(true/false)
It's a new param for now then it will not :smile: 
I think you should remove this comment, we understand that this column if a boolean type.

2022-05-24 14:52 UTC, sBouzols commented on src/components/network/config-tables.js
> +                boolean: true, // new param to indicate that this cell data is boolean(true/false)
You don't need a `cellDataGetter` here for `LoadTapChangingCapabilities`?

2022-05-25 08:08 UTC, JacquesBorsenberger approved these changes
not sure adding a new value for boolean type is the right approach, maybe we should use un columnType (for numeric, boolean...) but it is ok.

2022-05-25 13:58 UTC, sBouzols approved these changes
Code Review OK
Tests front ok
No warnings
Ok for the front, but hard to approve without data
No tests for sort, filter, or csv export because no data in columns

2022-05-25 14:02 UTC, bendaamerahm commented
> Code Review OK Tests front ok No warnings Ok for the front, but hard to approve without data No tests for sort, filter, or csv export because no data in columns

im working on adding data to json from back, ill informe you when data is ready to use

2022-05-25 14:05 UTC, bendaamerahm commented
> not sure adding a new value for boolean type is the right approach, maybe we should use un columnType (for numeric, boolean...) but it is ok.

ill do the refactoring for this change later  to avoid conflicts

2022-05-30 13:11 UTC, sBouzols requested changes

2022-05-31 15:20 UTC, sBouzols approved these changes

2022-05-31 15:30 UTC, merged