Prevent scrolling while editing line 2 windings transformers
gridsuite/gridstudy-app pull request #625
Opened 2022-06-23 14:35 UTC by anas-drissi

2022-06-28 11:38 UTC, etiennehomer requested changes

2022-06-28 11:38 UTC, etiennehomer commented on src/components/network/equipment-table.js
> +                                //disableVerticalScroll* Property put in network-table.js to know if we are in edit mode in 2 Widings Transformers
Why only in 2WT ? I think you can remove this comment

2022-06-28 11:38 UTC, etiennehomer commented on src/components/network/equipment-table.js
> +                                styleBottomLeftGrid={
You can remove this property as this scroll is already hidden

2022-06-28 11:48 UTC, EstherDarkish approved these changes

2022-06-28 11:48 UTC, EstherDarkish commented on src/components/network/equipment-table.js
> +                                //disableVerticalScroll* Property put in network-table.js to know if we are in edit mode in 2 Widings Transformers
You should remove this comment, it is misleading.

2022-06-29 08:29 UTC, etiennehomer approved these changes

2022-06-29 14:01 UTC, merged