Fix NAD layout when error
gridsuite/gridstudy-app pull request #651
Opened 2022-06-29 13:12 UTC by etiennehomer

2022-06-30 12:05 UTC, EstherDarkish requested changes

2022-07-01 09:35 UTC, EstherDarkish commented on src/components/diagrams/networkAreaDiagram/network-area-diagram.js
> +                    setSvg({
Ok, fixed.

2022-07-01 09:38 UTC, EstherDarkish approved these changes

2022-07-01 09:55 UTC, archendel approved these changes
Tested : OK

2022-07-01 12:32 UTC, jonenst approved these changes

2022-07-01 12:38 UTC, merged