deletion of badge if calculation invalidated
gridsuite/gridstudy-app pull request #714
Opened 2022-07-20 07:38 UTC by anas-drissi

2022-07-20 08:06 UTC, bendaamerahm requested changes

2022-07-20 16:04 UTC, anas-drissi commented on src/components/app-top-bar.js
> +                                ((loadflowNotif &&
it's fixed

2022-07-20 16:04 UTC, anas-drissi commented on src/components/app-top-bar.js
> +                            console.log(
it's ok

2022-07-20 16:04 UTC, anas-drissi commented on src/components/app-top-bar.js
> +                            console.log(
it's fixed

2022-07-20 16:05 UTC, anas-drissi commented on src/components/app-top-bar.js
> +                            console.log(
it's fixed

2022-07-22 09:41 UTC, etiennehomer commented
The badge for security analysis results is not deleted when the node is invalidated. 

Other problem: when we run a loadflow, then we invalidate the node (the badge is deleted). And then we run a security analysis, we have '2' in the badge instead of '1'

2022-08-04 13:59 UTC, FranckLecuyer approved these changes
Tests: OK
Code review: OK

2022-08-04 14:14 UTC, bendaamerahm approved these changes
code review : ok 
test: ok

2022-08-04 14:17 UTC, merged