Adapt button on create voltage level for line split and line attach hypothesis
gridsuite/gridstudy-app pull request #733
Opened 2022-07-27 11:52 UTC by FranckLecuyer

2022-07-27 12:03 UTC, laurgarn approved these changes

2022-07-27 15:27 UTC, niconoir requested changes

2022-07-27 16:06 UTC, FranckLecuyer commented on src/components/dialogs/line-attach-to-voltage-level-dialog.js
>              voltageLevelOrIdRef.current = voltageLevelOrId;
Removed

2022-07-27 16:06 UTC, FranckLecuyer commented on src/components/dialogs/line-split-with-voltage-level-dialog.js
>              voltageLevelOrIdRef.current = voltageLevelOrId;
Removed

2022-07-29 09:36 UTC, niconoir approved these changes

2022-07-29 09:44 UTC, merged