[WIP] Sensitivity analysis setting frontend
gridsuite/gridstudy-app pull request #750
Opened 2022-08-10 14:27 UTC by niconoir

2022-08-25 11:37 UTC, FranckLecuyer approved these changes

2022-09-09 08:52 UTC, geofjamg requested changes
Functional review: 
 - once sensitivity analysis dialog is open, I figured out that I didn't create my filters, so in gridexplore, I created my 2 filters. When trying to select just created filters, they were not available in the element chooser. I had to close sensitivity analysis dialog and re-open it to enable element chooser to see new filters again.
 - we should filter in element chooser what kind of filter are allowed: for instance I can select a generator based filter for monitored branches.

2022-09-12 11:28 UTC, FranckLecuyer commented
> 

- Technical story has been created to solve the contingency/filter selection pb : 

https://dev.azure.com/GridSuit/MVP/_workitem/edit/1291/

- Equipment type is not available in the filter metadata. A technical story has been created for that : 
https://dev.azure.com/GridSuite/MVP/_workitems/edit/1292/

2022-09-26 09:52 UTC, geofjamg approved these changes

2022-09-26 09:53 UTC, merged