Us 1146 2 fix voltage level creation in unbuilt substation
gridsuite/gridstudy-app pull request #755
Opened 2022-08-18 12:59 UTC by laurgarn

Fix regressions occasioned by first part

2022-08-19 13:15 UTC, archendel requested changes
Test KO :
When creating a voltage level, if there are some results returned by the elasticsearch request and the user presses "enter" or clicks somewhere else on the screen, the input is replaced by the first option suggested by the autocomplete system

2022-08-22 09:51 UTC, laurgarn commented
> Test KO : When creating a voltage level, if there are some results returned by the elasticsearch request and the user presses "enter" or clicks somewhere else on the screen, the input is replaced by the first option suggested by the autocomplete system

I checked out the commit before the merging of #713.
For in substation choice, as soon as the popup is open, the item nearest to the outer click will be selected.
For connection creation, the difference I notice is you can not longer input a "free" string or it will be emptied when leaving -> is it the misbehaviour you signal ?

2022-09-12 14:00 UTC, FranckLecuyer requested changes
Tests: 
when there are no equipements of a particuliar type in the delete equipment dialog, the 'Loading ...' message remains displayed ...

2022-09-12 14:10 UTC, laurgarn commented on src/components/dialogs/voltage-level-creation-dialog.js
> +                substationId: substation.id ?? substation,
Nice idea. Changed.

2022-09-12 14:29 UTC, laurgarn commented on src/components/dialogs/connectivity-edition.js
> +                        autoSelect
Outdated code. Was an intermediate in transition to useAutocompleteField

2022-09-12 15:03 UTC, laurgarn commented on src/utils/functions.js
> +/**
Re-routed to another PR.

2022-09-13 14:38 UTC, FranckLecuyer approved these changes

2022-09-23 10:12 UTC, archendel approved these changes

2022-09-23 12:41 UTC, merged