Change name of method which retrieves a study's case name
gridsuite/gridstudy-app pull request #760
Opened 2022-08-29 13:15 UTC by Meklo

2022-08-30 15:31 UTC, FranckLecuyer requested changes

2022-08-31 07:10 UTC, laurgarn approved these changes
Nothing suspect

2022-08-31 08:44 UTC, Meklo commented on src/utils/rest-api.js
>      console.info('Fetching case infos');
Changed

2022-08-31 08:49 UTC, FranckLecuyer approved these changes

2022-09-01 09:03 UTC, EstherDarkish reviewed
I cannot make it work, the front do not start due to this error :

```
Failed to compile.

./src/components/app.js
Attempted import error: 'Navigate' is not exported from 'react-router-dom'.
```

2022-09-01 11:55 UTC, EstherDarkish approved these changes

2022-09-02 09:52 UTC, merged