make the appearence of voltage values in sld consistent if loadflow i…
gridsuite/gridstudy-app pull request #785
Opened 2022-09-28 14:39 UTC by Walid-Sahnoun

…nvalid

Signed-off-by: walid-sahnoun <walid.sahnoun@rte-france.com>

2022-09-29 07:09 UTC, etiennehomer commented
You can do something more simple : you can retrieve the element <text class="sld-label" id="NODE_ACHIEP4_0_v" x="60.0" y="600.0">94.7 kV</text> with the methods getElementByClassName, getParent, getChildren...
And then you change its text context.

2022-09-29 07:31 UTC, geofjamg requested changes
Definitely not the right way to do it

2022-09-30 08:50 UTC, etiennehomer requested changes

2022-09-30 08:50 UTC, etiennehomer commented on src/components/diagrams/singleLineDiagram/single-line-diagram.js
> +                    if (nodeIdKV !== null && nodeIdKV !== undefined) {
if(nodeIdKV)

2022-09-30 08:50 UTC, etiennehomer commented on src/components/diagrams/singleLineDiagram/single-line-diagram.js
> +                    if (nodeIdAngle !== null && nodeIdAngle !== undefined) {
if(nodeIdAngle)

2022-09-30 08:50 UTC, etiennehomer commented on src/components/diagrams/singleLineDiagram/single-line-diagram.js
> +                            nodeIdKV = element[i].id.replace('circle', 'v');
You can build nodeIdKV and nodeIdAngle with : 
'NODE_' + sldId + '_0_v'

2022-09-30 09:25 UTC, etiennehomer commented on src/components/diagrams/singleLineDiagram/single-line-diagram.js
> +                let element =
rename to nodeInfos

2022-09-30 09:25 UTC, etiennehomer requested changes

2022-09-30 09:25 UTC, etiennehomer commented on src/components/diagrams/singleLineDiagram/single-line-diagram.js
> +                        if (element[i].id.endsWith('_circle')) {
you have to replace the text for each

2022-09-30 12:17 UTC, etiennehomer requested changes
Remove package-lock.json changes

2022-11-02 09:29 UTC, closed without merging