Move sld state from URL to sessionstorage
gridsuite/gridstudy-app pull request #795
Opened 2022-10-07 12:58 UTC by archendel

SLD state was stored in URL, we should now store it in session storage

2022-10-12 15:44 UTC, sBouzols requested changes
some comments will test

2022-10-17 12:34 UTC, archendel commented on src/redux/reducer.js
> +                // if sld is unpinned, the sld that had the state OPENED is now MINIMIZED
it is the current behaviour

2022-10-17 12:34 UTC, archendel commented on src/redux/reducer.js
> +            sldState[previouslyOpenedSldIndex].state = ViewState.MINIMIZED;
it is the current behaviour

2022-10-17 12:34 UTC, archendel commented on src/components/diagrams/singleLineDiagram/utils.js
> +    OPENED: 'opened',
will probably do in the future, in another PR

2022-10-17 12:35 UTC, archendel commented on src/components/diagrams/singleLineDiagram/single-line-diagram-pane.js
> +            if (state === ViewState.MINIMIZED) {
going to improve the code readability to make it clearer

2022-10-17 13:01 UTC, archendel commented on src/redux/session-storage.js
> +import { APP_NAME } from '../utils/config-params';
fixed

2022-10-18 15:29 UTC, niconoir approved these changes

2022-10-26 13:54 UTC, Walid-Sahnoun approved these changes

2022-10-28 11:06 UTC, sBouzols approved these changes

2022-11-08 15:03 UTC, sBouzols reviewed
some comments

2022-11-08 15:06 UTC, sBouzols approved these changes
Code Review ok (some ligth comments)
Tests done OK
* Duplicate tab on Firefox copy the content of sessionStorage, this is cool.
Console warning check OK

2022-11-09 09:41 UTC, archendel commented on src/redux/session-storage.js
> +    const sldState = JSON.parse(
fixed

2022-11-09 09:41 UTC, archendel commented on src/redux/session-storage.js
> +        return sldState.sldtate;
fixed

2022-11-09 09:41 UTC, archendel commented on src/redux/session-storage.js
> +            sldtate: sldState,
fixed

2022-11-09 09:43 UTC, archendel commented on src/components/diagrams/singleLineDiagram/single-line-diagram-pane.js
> +                            minimize={minimizeSld}
fixed

2022-11-09 15:12 UTC, jonenst approved these changes

2022-11-09 16:00 UTC, merged