Fix substation creation when name is empty or contain only spaces
gridsuite/gridstudy-app pull request #804
Opened 2022-10-13 08:27 UTC by Walid-Sahnoun

2022-10-13 08:42 UTC, FranckLecuyer approved these changes

2022-10-14 07:06 UTC, SlimaneAmar requested changes

2022-10-14 07:06 UTC, SlimaneAmar commented on src/utils/rest-api.js
> +function checkEquipementNameEmptyOrContainsOnlySpaces(name) {
Remove it

2022-10-14 07:06 UTC, SlimaneAmar commented on src/utils/rest-api.js
> +                checkEquipementNameEmptyOrContainsOnlySpaces(substationName),
substationName.trim() === '' ? null : substationName.trim()

2022-10-14 08:50 UTC, Walid-Sahnoun commented on src/utils/rest-api.js
> +function checkEquipementNameEmptyOrContainsOnlySpaces(name) {
done

2022-10-14 08:50 UTC, Walid-Sahnoun commented on src/utils/rest-api.js
> +                checkEquipementNameEmptyOrContainsOnlySpaces(substationName),
done

2022-10-14 11:18 UTC, closed without merging