Gray validate dialogue if no modification made
gridsuite/gridstudy-app pull request #807
Opened 2022-10-14 10:02 UTC by anas-drissi

2022-10-25 15:06 UTC, etiennehomer requested changes

2022-10-25 15:06 UTC, etiennehomer commented on src/components/dialogs/inputs/input-hooks.js
> +    const [hasChanged, setHasChanged] = useState(false);
Not used. You can remove it

2022-10-25 15:06 UTC, etiennehomer commented on src/components/dialogs/inputs/input-hooks.js
> +    return [value, field, hasChanged, setHasChanged];
Can be removed

2022-10-25 15:06 UTC, etiennehomer commented on src/components/dialogs/inputs/use-autocomplete-field.js
> +    const [hasChanged, setHasChanged] = useState(false);
Same. Not used

2022-10-25 15:06 UTC, etiennehomer commented on src/components/dialogs/inputs/use-autocomplete-field.js
> +    return [value, field, setValue, hasChanged, setHasChanged];
Same. Not used

2022-10-26 14:05 UTC, anas-drissi commented on src/components/dialogs/inputs/use-autocomplete-field.js
> +    return [value, field, setValue, hasChanged, setHasChanged];
It's fixed.

2022-10-26 14:05 UTC, anas-drissi commented on src/components/dialogs/inputs/use-autocomplete-field.js
> +    const [hasChanged, setHasChanged] = useState(false);
It's fixed.

2022-10-26 14:05 UTC, anas-drissi commented on src/components/dialogs/inputs/input-hooks.js
> +    return [value, field, hasChanged, setHasChanged];
It's fixed.

2022-10-26 14:26 UTC, etiennehomer commented
Tests ok, code ok

2022-10-26 14:40 UTC, bendaamerahm approved these changes
test: ok

2022-10-27 06:46 UTC, merged