Fix user disconnect
gridsuite/gridstudy-app pull request #811
Opened 2022-10-17 12:13 UTC by FlauFlauw

Unselect the current node when the user is disconnected
Fix npm warnings

2022-10-19 15:42 UTC, flomillot commented
Je viens de tomber sur #766 du coup j'abandonne la PR

2022-10-25 09:30 UTC, niconoir requested changes

2022-10-25 09:30 UTC, niconoir commented on src/components/app.js
> +    useEffect(() => {
I would have put this code in app-top-bar.js since it seems strange to me to handle the currentTreeNode redux storage so high in the hierarchy.

2022-10-25 13:25 UTC, niconoir approved these changes

2022-10-26 09:52 UTC, merged