editing labels in the create a 2 windings transformer form
gridsuite/gridstudy-app pull request #865
Opened 2022-11-15 08:18 UTC by anas-drissi

2022-11-15 15:28 UTC, sBouzols requested changes

2022-11-15 15:28 UTC, sBouzols commented on src/translations/fr.json
> +    "DeadbandMW":"Bande morte (MW)",
No, We should have only one translation for Deadband then add the unit in the input

2022-11-15 15:31 UTC, sBouzols requested changes

2022-11-15 15:33 UTC, sBouzols requested changes
You forget to change `Side1` and `Side2` to `OriginSide` and `ExtrimitySide` as well

2022-11-16 10:21 UTC, anas-drissi commented on src/components/dialogs/two-windings-transformer/two-windings-transformer-creation-dialog.js
> +            label: 'DeadbandKV',
it's fixed

2022-11-16 10:27 UTC, sBouzols approved these changes

2022-11-16 10:28 UTC, bendaamerahm approved these changes

2022-11-16 10:33 UTC, merged