Updating generator modification form
gridsuite/gridstudy-app pull request #938
Opened 2022-12-12 09:56 UTC by ayolab

Signed-off-by: Ayoub LABIDI <ayoub.labidi@protonmail.com>

2022-12-13 13:30 UTC, ayolab commented on src/components/dialogs/generator-modification-dialog.js
> +    const isReactiveCapabilityCurveOn = useCallback(() => {
you are right, changes done

2022-12-22 11:59 UTC, EstherDarkish commented on src/components/dialogs/inputs/input-hooks.js
> +                        {previousValue && doTranslation ? (
The second previousValue test seems redondant

2022-12-22 11:59 UTC, EstherDarkish commented on src/components/dialogs/inputs/reactive-capability-curve-table.js
> +function getPreviousValue(displayedPreviousValues, displayedValues, index) {
Can you explain the logic behind this function ? Why do we get the last array field in the first IF instead the indexed one ?

2022-12-22 12:12 UTC, EstherDarkish requested changes

2022-12-22 12:12 UTC, EstherDarkish commented on src/components/dialogs/inputs/reactive-capability-curve-table.js
> +function fixValuesFormat(valuesToFix) {
This function is bad. Why is it here ?
There is a bug if the value test is equal to zero. There are validation functions available for the job in the validation-functions.js file if needed.

2023-01-04 16:46 UTC, laurgarn approved these changes

2023-01-04 16:59 UTC, merged