create load scalable
gridsuite/gridstudy-app pull request #946
Opened 2022-12-12 16:21 UTC by bendaamerahm

Signed-off-by: bendaamerahm <ahmed.bendaamer@rte-france.com>

2023-01-09 16:27 UTC, FranckLecuyer requested changes

2023-01-09 16:27 UTC, FranckLecuyer commented on src/translations/network-modifications-en.json
> +    "network_modifications/LOAD_SCALING": "Load scalable {computedLabel}",
Load scaling

2023-01-09 16:27 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "LoadScalingError": "Erreur lors de la création de Variation plan de consommation",
Erreur lors de la création de la variation du plan de consommation

2023-01-09 16:27 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "TanFixed": "tan(φ) fixe",
TanPhiFixed

2023-01-09 16:27 UTC, FranckLecuyer commented on src/translations/en.json
> +    "TanFixed": "tan(φ) fixed",
TanPhiFixed

2023-01-09 16:27 UTC, FranckLecuyer commented on src/translations/en.json
> +    "LoadScaling": "Load scalaing",
"Load scaling"

2023-01-09 16:27 UTC, FranckLecuyer commented on src/components/network/constants.js
> +    { id: 'TAN_FIXED', label: 'TanFixed' },
TAN_PHI_FIXED

2023-01-10 14:48 UTC, FranckLecuyer requested changes
Tests : 
Some active variation mode values and some reactive variation mode values are not completely visible in language EN

2023-01-10 14:48 UTC, FranckLecuyer commented on src/components/dialogs/load-scaling-dialog.js
> +const REACTIVE_VAR_MODE_DEFAULT_VALUE = 'TAN_FIXED';
TAN_PHI_FIXED

2023-01-10 16:58 UTC, FranckLecuyer requested changes

2023-01-10 17:30 UTC, bendaamerahm commented on src/components/graph/menus/modification-list-item.js
> +            return modif.uuid;
to check with our PO

2023-01-11 14:19 UTC, FranckLecuyer requested changes
Tests:
Adding or deleting a filter does not enabling the 'Validate' button

2023-01-13 14:51 UTC, FranckLecuyer approved these changes

2023-01-13 14:51 UTC, FranckLecuyer commented on src/components/graph/menus/modification-list-item.js
> +        } else if (modif.type === 'LOAD_SCALING') {
remove this case : no uuid will be appended to generic load scaling label

2023-01-13 14:52 UTC, FranckLecuyer requested changes
See remaining remarks

2023-01-13 15:38 UTC, FranckLecuyer approved these changes

2023-01-19 09:48 UTC, SlimaneAmar approved these changes

2023-01-19 11:29 UTC, merged