fix graying flesh and values in sld when loadflow invalid
gridsuite/gridstudy-app pull request #951
Opened 2022-12-13 15:42 UTC by Walid-Sahnoun

Signed-off-by: walid-sahnoun <walid.sahnoun@rte-france.com>

2022-12-14 11:15 UTC, etiennehomer approved these changes

2022-12-14 16:16 UTC, geofjamg requested changes
should be '& .sld-active-power, .sld-reactive-power, .sld-voltage, .sld-angle'

sld-arrow-p and std-arrow-q do not exist anymore.
std-out and sld-in are for a different purpose

2022-12-15 14:29 UTC, etiennehomer approved these changes

2022-12-15 14:36 UTC, geofjamg commented on src/components/diagrams/singleLineDiagram/single-line-diagram.js
> +                    console.log(data.svg);
Could you clean this log?

2022-12-15 16:44 UTC, geofjamg approved these changes

2022-12-15 17:20 UTC, sBouzols approved these changes

2022-12-15 18:42 UTC, merged