[WIP] Add generator scalable modification
gridsuite/gridstudy-app pull request #974
Opened 2022-12-27 20:26 UTC by YenguiSeddik

2023-01-10 13:15 UTC, FranckLecuyer requested changes

2023-01-10 13:15 UTC, FranckLecuyer commented on src/translations/network-modifications-en.json
> +    "network_modifications/GENERATOR_SCALING": "Creating generator scalable {computedLabel}",
Creating generator scaling {computedLabel}

2023-01-10 13:15 UTC, FranckLecuyer commented on src/translations/fr.json
> +    "GeneratorScalingError" : "Erreur lors de la création de Variation plan de consommation",
Erreur lors de la création de la variation du plan de production

2023-01-10 13:15 UTC, FranckLecuyer commented on src/translations/en.json
> +    "GeneratorScaling": "Generator scalable",
: "Generator scaling"

2023-01-10 16:24 UTC, FranckLecuyer requested changes

2023-01-10 16:58 UTC, FranckLecuyer requested changes

2023-01-10 16:58 UTC, FranckLecuyer commented on src/components/graph/menus/modification-list-item.js
> +            return modif.uuid;
displaying the modification uuid is useless for the user ... 
Maybe we should set a name in the modification creation dialog ?

2023-01-11 10:19 UTC, FranckLecuyer requested changes
Tests: 
'Iterative' mode change is not persistent (when reopening the dialog, it is always checked, even if it was previously unchecked by the user
'Iterative' mode is always 'false' in the database, even if it was checked by the user
Adding or deleting a filter does not enabling the 'Validate' button
'Stacking up' mode with 'target P' mode does not function (see remarks on back concerning the sum value not calculated)

2023-01-13 13:18 UTC, FranckLecuyer approved these changes

2023-01-25 10:03 UTC, SlimaneAmar commented on src/utils/rest-api.js
> +    }
let generatorScalingUrl = getStudyUrlWithNodeUuid(studyUuid, currentNodeUuid) +'/network-modifications';
if (modificationUuid) {
    generatorScalingUrl = generatorScalingUrl + '/' + encodeURIComponent(modificationUuid);
}

2023-01-25 10:05 UTC, SlimaneAmar commented on src/translations/fr.json
> +    "EmptyList/variations": "La liste de variations est vide",
La liste de**s** variations est vide

2023-01-31 08:15 UTC, merged