add 2wt regulated terminal
gridsuite/gridstudy-app pull request #992
Opened 2023-01-09 10:00 UTC by AbdelHedhili

Signed-off-by: Abdelsalem <abdelsalem.hedhili@rte-france.com>

2023-01-09 10:06 UTC, AbdelHedhili commented
There are a lot a warning triggered in the console when handling the creation form, any idea where does it come from ? I don't have a clue.

2023-01-11 09:27 UTC, bendaamerahm approved these changes
code review ok

2023-01-23 15:14 UTC, archendel requested changes
between "ratio tap changer" tab and "phase tap changer" tab, there is a small difference

when Voltage Regulation is unchecked, "regulated side" is marked (optional) in "phase tap changer" tab, but not in the other one

now testing full workflow

2023-01-23 15:14 UTC, archendel commented on src/translations/en.json
> +    "RegulatedSide": "regulated side",
```suggestion
    "RegulatedSide": "Regulated side",
```

2023-01-23 15:14 UTC, archendel commented on src/translations/fr.json
> +    "RegulatedSide": "côté reglé",
```suggestion
    "RegulatedSide": "Côté réglé",
```

2023-02-09 08:46 UTC, closed without merging